nationalarchives/ds-wagtail

sass/etna.scss, sass/includes/_alert-message.scss, templates/base.html, templates/includes/alert-message--high.html, templates/includes/alert-message--low.html, templates/includes/alert-message--medium.html
Hi @gtvj 
Here is the PR for the alert message component, relating to https://national-archives.atlassian.net/browse/DS-233 
I have checked it on:
- Chrome, MacOS X
- Firefox, Windows 10
- IE11, Windows 10
A couple questions:
- Do these need a `role="alert"`? VoiceOver seemed to read them out first anyway, since they're the first elements on the page.
- Should I ask a designer to look over this before merging?
Thanks :+1:
=> Introduce alert-message component

etna/home/templates/home/home_page.html, templates/collections/category_page.html, templates/collections/explorer_page.html, templates/includes/card-group-secondary-nav-time-period.html, templates/includes/card-group-secondary-nav.html
Hi @gtvj,
Would you be able to look at this PR?
It adds some HTML includes/static content to the homepage to match the UXPin Mockup in 
https://national-archives.atlassian.net/browse/DS-232
I have also changed the  card loops to use `page.get_children.specific`  instead of `page.get_children`, as Dan B let me know that without the `.specific`, you can only access fields on the default Wagtail Page class, instead of the extra fields that have been added to the Page via  the `models.py` file. So in this case,  I have made it so that `{{child.introduction}}` is accessible in the cards, so that their description texts are dynamic.
Here's a screenshot of the homepage with the same  cards as the UXPin:
Note that in the UXPin, the cards have a "NEW" label next  to them, however we decided this …
=> DS 232 Frontend

etna/ciim/client.py, etna/ciim/models.py, etna/ciim/tests/test_client.py
Small tidy to the Kong client.
I've replaced code where `KongClient` directly accesses `django.conf.settings` in favour of `__init__` params
=> Replace settings access with init params in client

sass/etna.scss, sass/includes/_blog-embed.scss, sass/includes/_box-out.scss, sass/includes/_content-block.scss, sass/includes/_global.scss, sass/includes/_key-facts__author.scss, sass/includes/_media-embed.scss, sass/includes/_record-embed.scss, sass/includes/_record-embed__no-image.scss, sass/includes/_research-resources.scss, sass/includes/_section-separator.scss, templates/includes/blog-embed.html, templates/includes/box-out.html, templates/includes/content-block.html, templates/includes/media-embed--audio.html, templates/includes/media-embed--video.html, templates/includes/record-embed--no-image.html, templates/includes/related-content.html, templates/includes/research-resources.html, templates/insights/insights_page.html, templates/quotes/blocks/quote.html
Would you be able to merge this branch?
This contains the following fixes:
- The `100vw` fix
- Renaming `callout` to `box-out`
- Fixing some issues with the icons. The URLs were incorrect. Also, as the `border-radius` was applied directly to the `<img>` tag, the images were being cut off by this `border-radius`. Therefore I've changed them to `<div>` elements with `background-image` which doesn't get affected by `border-radius`. Hopefully this is OK.
- Preventing `sr-only` elements appearing as contrast issues (by giving them a `background-color` and `color` even though they're never visible) This is just so they don't pollute the WAVE/Lighthouse issues across the whole application.
Would you be able to merge if this is OK?
Thanks :+1:
=> Insights styling fixes

README.md
This is no longer relevant since we are using the SASS directly within the repo.
=> Remove line that says toolkit CSS is loaded

etna/collections/tests/test_views.py, etna/records/views.py
Update call to Kong to only present evidential data in `RecordChooser`
=> Only show evidential records in record chooser DS-256

etna/insights/migrations/0008_add_teaser_image.py
CommandError: Conflicting migrations detected;
multiple leaf nodes in the migration graph:
(0007_add_section_block, 0007_add_teaser_image in insights).
=> Fix migration conflict in insights

templates/collections/results_page.html
It fixes a styling issue on the explorer results page - if you don't have the Kong environment variables you can only see this page on the live environment at https://www.main-bvxea6i-rasrzs7pi6sd4.uk-1.platformsh.site/explore-the-collection/explore-by-topic/arts-and-culture/the-design-registers/ 
I changed it to this:
Thanks :+1:
=> Remove generic-intro from results page intro text

templates/quotes/blocks/quote.html
Hi @danbentley - I hadn't realised that _not_ using `static` within the path would cause an error (my previous PR had updated the code to ensure that where `static` was used it had been loaded). I've done quite a thorough search through the code and I think this is the only instance of a local `src` attribute that doesn't use `static`.
=> Update all 'src' paths to use 'static'

templates/insights/blocks/promoted_item.html
Hi @gtvj,
Would it be possible to have a look at this PR? It implements the teaser image for promoted items (e.g. a blog embed) in the same fashion as the hero image so that the image isn't distorted as the screen is resized. Thank you 👍
=> Amend promoted item teaser image implementation

etna/ciim/tests/factories.py, etna/ciim/tests/test_models.py, etna/ciim/tests/test_utils.py, etna/ciim/utils.py, etna/records/converters.py, etna/records/tests/test_urls.py, etna/records/transforms.py, templates/includes/card-group-record-summary-no-image.html, templates/records/record_disambiguation_page.html
Some disambiguation pages returned data that couldn't be parsed into a `RecordPage`.
Additionally, the `datalayer` template tag raised an error because there's no page object to query.
=> Fix disambiguation page

templates/500.html
Hi @JamesWChan - could you have a look at this PR. It's just moving the `dataLayer.push()` above the GTM script.
=> Move GTM script below the dataLayer push

sass/includes/_pagination.scss, templates/includes/card-group-record-summary-no-image.html, templates/records/record_disambiguation_page.html
This introduces:
1. the same component pattern HTML for pagination as is used in other places (directly in the view)
2. uses the `truncatewords` Django [built-in filter](https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#truncatewords) to truncate descriptions within `card-group-record-summary-no-image.html`
=> Style disambiguation pagination and trucate item descriptions

templates/includes/generic-intro-with-prefix.html, templates/includes/generic-intro.html
This is just a quick change to prevent an issue which is currently present on the record disambiguation page (that I've just spotted). I've just added a condition to prevent a `<p>` being rendered empty.
=> Add condition to prevent page.subheading being rendered empty

etna/records/tests/test_blocks.py, etna/records/widgets.py
It's possible that a referenced record on an insights or results page isn't available in Kong, this fix ensure the edit page is still accessible.
=> Ensure the edit page is still accessible even if a record isn't available in Kong

templates/collections/results_page.html, templates/includes/results-intro-with-prefix.html
From UAT we have been asked to add the text 'Selected highlights of' which makes this a non-general include. It retains the component HTML but, to avoid confusion, I have renamed the include.
=> Make generic-intro-with-prefix specific to Results

templates/includes/card-group-record-summary.html
`teaser_image` for a record on the results page is optional.
Images should be associated with all highlight records for launch but currently many of them don't have images yet.
=> Fix issue where record doesn't have a teaser image

sass/includes/_media-embed.scss, templates/media/blocks/media-block--audio.html, templates/media/blocks/media-block--video.html
Hi @gtvj,
This PR puts the transcript within a `<details>` element so it can be toggled. This is to solve the issue where a very long transcript would result in a very long webpage.
Thank you 👍
=> Put transcript in details element

poetry.lock
Wagtail 2.14 changes the way blocks are handled. This unfortunately has broken the `RecordChooser` and associated tests.
Keeping this change out of `main` while I look at a fix.
This reverts commit d61daec4852ddf5971d6a667c3d058105ff20b1c.
=> Revert "Update Wagtail v2.14.1"

sass/includes/_pagination.scss
I noticed on the Beta site that there's a margin bottom on the pagination component which seems to have been inherited by the list. This PR overrides that.
=> Fix the padding bottom on browse pagination

sass/etna.scss, sass/includes/_xslt-patches.scss, templates/includes/records/record-details.html
We were asked by the data team to provide add CSS in order to improve the presentation of XLST generated markup which appears within the Record Description block of details pages. This included a request to make spans appear to be list items.
I have explained that using CSS to make HTML that lacks appropriate semantics appear as it would if the correct semantics were in place would fail a [Level A WCAG Success Criterion 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html). and that the best I can do is to introduce some padding.
It has been acknowledged by data colleagues that this is an issue which needs to be addressed at source.
=> Add CSS to provide some spacing around XSLT generated markup

templates/404.html
Having been contacted by analytics colleagues this morning to add a title to the 404 page I noticed that base.html relies upon values that are not available in the 404 page.
Having done a bit of research online it seems the default 404 view provides two variables to the view: `request_path` and `exception`. It might be that `exception` would allow us to add a condition to `base.html` but since I can't set `DEBUG` to `False` (which I'd need to do in order to examine `exception`) it seemed most pragmatic to replicate the static content of base.html within 404.html
=> Add title to 404 page

sass/includes/_hierarchy-global-nav.scss, sass/includes/_hierarchy-local-nav.scss, sass/includes/_record-access-options.scss, scripts/src/details.js, scripts/src/explorer.js, scripts/src/image-browse.js, scripts/src/insights.js, scripts/src/modules/analytics/add_unique_ids.js, scripts/src/modules/analytics/push_reference_and_series.js, templates/collections/blocks/time_period_explorer.html, templates/collections/blocks/topic_explorer.html, templates/home/blocks/featured_external_page.html, templates/home/blocks/featured_page.html, templates/includes/card-group-promo--dark.html, templates/includes/card-group-promo--green.html, templates/includes/card-group-secondary-nav-time-period.html, templates/includes/card-group-secondary-nav.html, templates/includes/footer.html, templates/includes/records/hierarchy-local.html, templates/includes/records/record-details.html, templates/includes/records/taxonomy-tags.html, templates/insights/blocks/featured_record.html, templates/insights/blocks/featured_records.html, templates/insights/blocks/related_item.html, templates/media/blocks/media-block--audio.html, templates/media/blocks/media-block--video.html
This PR includes further changes from the front end review and some additional analytics requirements that have been requested. The full changes are: 
**Related considerations**
I've found something odd happening with headings in the Letter from Cyril to Morris insights page. We’ve got two headings at different levels that are identical. They are:
- `<h2>` Transcript of the letter
- `<h3>` Transcript of the letter
It seems the `<h3>` - which is presented only to screen readers - is redundant. I think this is going to come up in the accessibility audit as something which is annoying to users. Looking at the editorial interface it seems these are coming from the **Section Heading** component and the **Quote** component - both of which require a heading. It seems in this circumstance we need …
=> Front end fixes - Part 2

templates/collections/results_page.html, templates/includes/card-group-record-summary-no-image.html, templates/includes/card-group-record-summary.html, templates/records/record_disambiguation_page.html
Hi @gtvj 
This PR:
- Gives the result card images an empty alt tag `alt=""`. I didn't use `role=presentation` here due to your commit message here: https://github.com/nationalarchives/ds-wagtail/commit/d5d1eb7029a73c2b3ea7d0f22b7d6ca31293753e
- Changes record summary cards to use `<h3>` elements for their titles.
- Adjusts the explorer results page and record disambiguation page headings, to preserve good structure since the card titles are now `<h3>` elements.
Thanks :+1:
=> Fix explorer issues identified in accessibility testing

sass/includes/_hierarchy-global-nav.scss, templates/base-images.html, templates/includes/records/hierarchy-global.html, templates/includes/records/image-viewer-panel.html, templates/records/image-browse.html, templates/records/image-viewer.html
=> Details page fixes

templates/includes/card-group-record-summary.html
Hi @gtvj,
This addresses a HTML issue where a figcaption can only be a first or last child of a figure. I simply removed the figcaption from the div and kept the class. I've tested on Firefox, Chrome and IE11.
Thanks :+1:
=> Move figcaption outside of div on explorer record cards

scripts/src/details.js, scripts/src/modules/scroll_to_bottom.js
Hi @gtvj,
This PR modifies the scroll_to_bottom function to work in IE11 (the previous approach, which used `scrollTo`, is not compatible with IE). I've tested on Chrome, FF, IE, Edge, and Safari and didn't see any issues. Would it be possible to merge if you are happy?
Thank you 👍
=> Refactor scroll_to_bottom so that it works in IE11

sass/includes/_footer.scss, sass/tna-toolkit/_footer.scss, sass/tna-toolkit/tna-toolkit.scss, templates/includes/footer.html
This commit fixes #187
The changes include: 
* Making the logos presentational, as recommended by DAC
* Exposing the name of the platform below the icon (so that people don't have to rely upon hover or recognition of the logo)
* A slight change to column width (to accommodate different zoom levels - it rendered correctly up to 500% zoom in testing)
I've tested this using LambdaTest again Chrome, Firefox, Safari, Edge, IE11, Android (Chrome) and iOS (Safari)
This required a change to a TNA toolkit stylesheet which is now redundant and has therefore been removed.
=> Fix social media link accessibility

config/settings/base.py, etna/users/forms.py, sass/includes/_forms.scss, templates/account/login.html
This PR fixes #166 by introducing links from the error summary to the relevant field. 
It is mostly straightforward but note the approach to update error message text.
=> Add links to relevant fields within error summary

sass/includes/_media-embed.scss
Hi @AshTNA,
This PR just removes the styling on the `&__audio-container` which was applying `margin-right: -3rem` and `margin-left: -3rem` as it was causing a spacing issue when viewing an insights page on mobile. I've checked the change in Chrome, Edge, Firefox, IE11, and Safari in LambdaTest and didn't spot any issues.
Would it be possible to merge if you are happy? Thank you 👍
=> Remove negative margin from audio container

README.md, fabfile.py
I've added these fab commands locally to make it easier to do most common things, so thought I might as well contribute them back (along with some documentation changes).
Fabric can be installed everywhere that Python can, so is a great option for simplifying this sort of thing on Django projects.
=> Chore: Add fabric commands for common tasks

config/settings/base.py, config/settings/dev.py
Having `BIRDBATH_REQUIRED = True` in dev settings is problematic for those who have not pulled data from a live environment and still want to run the app.
Since the `pull-production-data` command runs birdbath automatically, I think it's safe enough to remove these settings overrides.
=> Chore: Tweak data anonymisation settings

README.md
Explains that superuser will need to be recreated after having run `fab pull-production-data`. While this information is output on the terminal when the command is run it is easily missed and the inclusion of it in the README is to make it more evident alongside other steps outlined there.
=> Add superuser re-creation instruction to README

config/settings/base.py
`wagtailmedia` was recently upgraded in another PR, and we failed to spot that our custom config was no longer being respected (the format for configuration changed - without warning - to use a single dictionary). This was most likely missed because nobody had content locally, and so couldn't see the impact of the change. Hopefully, now that realistic content is available to pull down from other environments, this sort of thing should be much easier to spot in future.
=> Update wagtailmedia config to match the new format (0.8+)

templates/includes/records/hierarchy-local.html
Added sr-only span with required link text to make links more accessible to screen reader users, which fixes #172.
=> Added sr-only span with required text to fix issue

sass/includes/_card-groups.scss
I noticed a small issue with the record summary cards that have a title that's more than one line long. I think we didn't see it as we only looked at records with a short title.
It looks like this because of a `display: inline` I added:
I fixed it by changing it to an `inline-block`, and I've checked it in Firefox, IE11 and Chrome.
Thanks :+1:
=> Change record-summary link to inline-block

README.md, fabfile.py
For `enable_platform_ssh()`:
* Use os.path.expanduser to get a platform-specific known_hosts path
* Use ssh-keygen to remove existing keys before adding a new one
General:
* Use subprocess.run() instead of local() for docker commands, as `shlex.escape()` doesn't work for windows
=> Fix: Windows compatibility changes 'pull-data' operations

.platform.app.yaml, Dockerfile
`poetry install` raised: `AttributeError: 'Link' object has no attribute 'is_absolute'` during build on platform.sh.
It appears that it's possible for poetry-core to update even if poetry is locked. Our issue was a caused by a regression introduced in 1.0.4.
Updated poetry following the advice in the linked github issue and updated pip to fix an issue selecting the correct wheel for cryptography `36.0.0` on platform.sh.
Locked Poetry to `1.1.12` and pip to `21.3.1` for docker and platform.sh
- [Link object being passed instead of Path to poetry.core.packages.file_dependency.FileDependency in poetry-core 1.0.5](https://github.com/python-poetry/poetry/issues/4541)
- [fix: Broken cache on Windows #4531](https://github.com/python-poetry/poetry/pull/4531)
=> Fix poetry install issue on platform.sh.

sass/includes/_content-block.scss, sass/includes/_promoted-item.scss, sass/includes/_quote.scss
Hi @AshTNA,
Would it be possible to merge this if you are happy? It reduces the text width on insights pages and uses `margin: auto` to keep everything centred. Thank you 👍
=> Reduce width of main body text

etna/analytics/mixins.py, etna/analytics/templatetags/datalayer_tags.py, etna/collections/models.py, etna/core/models/basepage.py, etna/records/models.py, templates/base.html, templates/base_page.html, templates/collections/explorer_index_page.html, templates/collections/results_page.html, templates/collections/time_period_explorer_index_page.html, templates/collections/time_period_explorer_page.html, templates/collections/topic_explorer_index_page.html, templates/collections/topic_explorer_page.html, templates/home/home_page.html, templates/includes/gtm-datalayer.html, templates/insights/insights_index_page.html, templates/insights/insights_page.html, templates/records/record_detail.html
The aim of this PR is to lay the groundwork for individual datalayer enhancement tickets by providing a more convenient way for page classes (and record/result classes) to make type-specific additions/changes.
In the process, I also:
- Simplified the way datalayer code is rendered (a simple tag that renders to a template)
- Introduced a `base_page.html` template where page-specific template code can live - Allowing us to remove a large amount of repeating code from individual page templates
- Used the `{% wagtail_site %}` tag in `base.html` to derive the 'current site' from the request (which is then cached and used for other things)
=> CHORE: Prep for datalayer tickets DF-74 + UN-141

etna/ciim/client.py, etna/ciim/tests/test_client.py
Updates to `KongClient.search`:
- Remove `show_buckets` (replaced with `aggregations=["groups"]`)
- Add `aggregations` param and associated `Aggregation` enum
- Add `filter_aggregations` param to support filtering
- Add `filter_keyword` to support search within
`KongClient.search_all`:
- `keyword`
- `size` number of items to return
- `from` offset results set
- `filter_aggregations` to support filtering
- `aggregations` aggregation data to include with results
=> Add support /search params and /searchAll. DF-150

docker-compose.yml, etna/ciim/client.py, etna/ciim/models.py, etna/ciim/tests/test_client.py, etna/collections/tests/test_views.py, etna/records/tests/test_views.py, etna/records/views/choosers.py, etna/records/views/records.py, etna/users/tests/test_access.py
Fixes disambiguation page and record chooser.
Let me know if you have any questions
=> DF-186 Add support for `/searchUnified` to API client

templates/search/blocks/search_buckets.html
From DF-158:
> The bucket links will also need an `aria-current=true` if it is the selected one. The bucket `<li>` elements will need a  `data-current=true` or `data-current=false` depending on if it is selected, for a JavaScript enhancement on mobile.
=> Add logic to highlight selected bucket

etna/search/forms.py, etna/search/tests/test_forms.py
Even though they are useful as a label source, the choice values we have for the `collection` field are not complete enough to be used for validation... a selected collection shouldn't be considered invalid just because it isn't in the hardcoded choice list.
=> DF-229: Disable validation for 'collection' field in search

etna/records/templatetags/records_tags.py
The tag is currently using the wrong URL parameter names, so this PR fixes that first of all. However, even when that problem is resolved, some record values simply don't match up to the format we're expecting, so this also updates the tag to handle those situations better.
We need to look much more in-depth at the URLs and accepted patterns in Etna and the API anyway, but that will happen separately.
=> CHORE: Update {% record_url %} tag to better account for edge cases

etna/insights/blocks.py, etna/insights/migrations/0039_alter_insightspage_body.py, templates/insights/blocks/promoted_item.html
Resolves ticket: https://national-archives.atlassian.net/browse/UN-183
As per discussion from [this comment](https://national-archives.atlassian.net/browse/UN-183?focusedCommentId=20523) and upwards, adding a simple category select back in, which can be picked up by Google Tag Manager.
=> UN-180: Add category choice field to PromotedItemBlock

config/settings/base.py, config/urls.py, config/versioning.py, docs/infra/configuring-an-environment.md, docs/infra/testing-an-environment.md, poetry.lock, pyproject.toml
Resolves ticket: https://national-archives.atlassian.net/browse/DF-123
Can be tested locally by setting the `SENTRY_DSN` env var to the relevant value (see ticket for more details), as well as the following:
- `SENTRY_ENVIRONMENT=local`
- `SENTRY_DEBUG_URL_ENABLED=True`
You should unset these values after testing is complete, as you should be using Django's built-in debugging tools locally, which are free!
=> DF-123: Sentry Integration

etna/records/blocks.py
Resolves Sentry issue: https://sentry.io/organizations/the-national-archives/issues/3264948158/?project=6377027
- Avoid calling fetch_all() if there are no `iaid` values to search with
- Rejig code to improve readability
=> Fix: KongBadRequestError raised from RecordChooserBlock.bulk_to_python()

sass/includes/_featured-record.scss, sass/includes/_insights.scss, templates/insights/blocks/featured_record.html, templates/media/blocks/media-block--audio.html, templates/media/blocks/media-block--video.html
Hi @AshTNA,
Could you have a quick look at this PR? It's just a couple of quick FE fixes for the Insight pages:
- Removes icons from media components
- Reduces padding on smaller screens (500px and below)
- Removes the record description from the featured record component (this was requested)
Thank you 👍
=> Fix: Insights fe fixes

sass/etna.scss, sass/includes/_content-warning.scss, templates/includes/content-warning.html
Hi @AshTNA,
Could you have a look at this small PR? It just adds the frontend for the content warning component. I've put an `aria-label` on the element to communicate its purpose to screen readers. I haven't added `role="alert"` to this component because going by MDN's documentation:
"Because of its intrusive nature, the alert role must be used sparingly and only in situations where the user's immediate attention is required."
I don't think this component needs to be highlighted to the user immediately and they will encounter it before they reach the content anyway.
=> UN 149: Trigger/content warning for specific content

etna/records/transforms.py
Account for situations where 'description' has multiple entries, and the one we are interested in isn't the first item.
Resolves Sentry issue: https://sentry.io/organizations/the-national-archives/issues/3266139263/
=> Fix: Transformation function erroring on multi-faceted record descriptions

sass/includes/search/_long-filters.scss, sass/includes/search/_search-filters.scss, scripts/src/catalogue-search.js, scripts/src/modules/search/search-long-filters.js, templates/search/catalogue_search_long_filter_chooser.html
Would you be able to merge this PR?
It relates to https://national-archives.atlassian.net/browse/DF-210
It adds a search component to the 'long filters' page on Search, which allows the list of filters to be narrowed down via a keyword. It works by:
- Grabbing the NodeList of filter`<li>` elements
- Converting the list into an Array
- Running `filter()` on this array to grab the narrowed down filters
- Rendering these narrowed down filters in the DOM
It will also always show any filters that the user has checked, so that they don't have to delete their keyword and then scroll through all the filters to see which ones are checked.
Accessibility wise, initially we were going to use `aria-live='polite'` to always update users on how many filters were being shown. However it …
=> DF-210: Make filters list in long filter page searchable

templates/includes/card-group-record-summary-no-image.html, templates/includes/card-group-record-summary.html, templates/includes/records/hierarchy-global.html, templates/includes/records/hierarchy-local.html, templates/includes/records/record-details.html, templates/includes/records/record-related-records.html, templates/insights/blocks/featured_record.html, templates/records/image-browse.html, templates/records/image-viewer.html
This is an extension of the work started by @AshTNA in #340, and a pre-requisite for one of the things we're looking to try out ahead of Insights launch.
=> DF-253: Use {% record_url %} everywhere for record links

sass/includes/_section-separator.scss
Would it be possible to merge this PR? It's just a small one that adds some `padding-right` to the Insights headings to prevent the heading text from overlapping the mobile icons. Thank you!
=> Add padding right to prevent heading text from overlapping icons on mobile

config/settings/base.py, etna/core/context_processors.py, etna/records/templatetags/records_tags.py, templates/includes/card-group-record-summary-no-image.html, templates/includes/card-group-record-summary.html, templates/insights/blocks/featured_record.html, templates/insights/blocks/featured_records.html
Relates to: https://national-archives.atlassian.net/browse/DF-319
Allows us to toggle whether record links in editorial content should link off to discovery OR be rendered by the in-progress record detail view from this project.
1. Find an Insights page that uses the "Featured Record" block (Alice Hawkins worked for me) and view it. The link to the record should display as before, linking to the same-site URL.
2.  Add ```FEATURE_RECORD_LINKS_GO_TO_DISCOVERY = True``` to `config/settings/dev.py` and save.
3. Refresh the Insights page.. the record should now be rendered with a link to view the record on discovery, instead of on the same site.
=> DF-319: Conditionally direct users to Discovery to view editor-selected records

etna/search/templatetags/search_tags.py, templates/search/blocks/featured-search__interpretive-card.html, templates/search/blocks/featured-search__record-creator.html, templates/search/blocks/featured-search__results-block.html
As outlined in https://national-archives.atlassian.net/browse/DF-328, some places were missed when we introduced the `{% record_url %}` tag. This PR updates the includes used in the [All Results](https://develop-sr3snxi-rasrzs7pi6sd4.uk-1.platformsh.site/search/featured/) view, so that results link to working URLs.
=> DF-328: Fix 'all results' record urls

sass/includes/_featured-insight.scss, sass/includes/_hero-image.scss, sass/includes/_media-embed.scss, sass/includes/_quote.scss, sass/includes/_section-image.scss, templates/insights/blocks/featured_record.html, templates/insights/blocks/featured_records.html, templates/insights/insights_index_page.html
Would it be possible to have a look at this PR? It implements some Insights tweaks that were requested by the team. It's mostly just CSS changes but I have changed the implementation of the featured insights image to be a `<div>` with a background as opposed to using the `<picture>` element with several `<source>`s. I did this because the `<picture>` implementation was dependent on explicitly defining image dimensions in pixels and I don't think it responds well depending on the screen size. I found going with the `<div>` with a background approach was more responsive (happy to have a call to demo and explain this further, it's a bit tricky to explain over text). Thank you 👍
=> UN-213: Front end tweaks

config/settings/test.py, etna/ciim/tests/test_models.py, etna/collections/tests/test_views.py, etna/records/tests/test_blocks.py, etna/records/tests/test_views.py, fabfile.py
Test code is very often difficult enough to understand, so the more we can do to centralise test configuration and simplify the test module code, the better.
Essentially, we don't want our unit tests to ever be making live requests to Kong - so, it makes sense that this configuration is always set when testing.
=> CHORE: Test configuration tweaks

sass/includes/_related-resources.scss, scripts/src/modules/analytics/insights_tracking/link_list_tracking.js, scripts/src/modules/analytics/insights_tracking/set_mobile_tracking_attributes.js, templates/insights/blocks/promoted_list_block.html
Hi @sdwilkes,
Would it be possible to have a look at this PR? It just a small modification to the analytics implementation - it starts the indexing for the mobile heading positions at 0 (rather than 1, which is what it was previously) and it slightly modifies how the position indexes are generated for links within `Linked list` components - it used to reset to 0 for each `Link list` component on a page but I've changed it so the position just keeps incrementing (Helen requested that I do this).
And although not related to analytics, I noticed a font size inconsistency in this component so I added on a commit to fix that.
=> UN-195: Tagging requirements for HTML

etna/records/tests/test_templatetags.py
Pre-requisite of #345, so that we can see the impact those changes have on `{% record_url %}` results.
=> CHORE: Add tests for record_url tag

sass/includes/search/_global-search.scss, scripts/src/modules/search/global-search.js
Would it be possible to have a look at this PR? It's just a very small change to make the text for the search tab behave consistently when it's a `<button>` and when it's an `<a>` tag. Thank you 👍
=> DF-222: Redesign header navigation to be a hamburger menu on mobile

sass/includes/_global.scss, templates/includes/header.html, templates/static/images/icons/open-in-new-tab.svg
Would it be possible to have a look at this PR? It just adds a link to The National Archives website above the header. I've tested this in Chrome, Firefox, Safari, Edge, and IE11 with no issues and I've attached a screenshot below for an example:
Thank you 👍
=> DF-301: Add 'Go to the current National Archives website' link to header

scripts/src/modules/hamburger-menu.js, scripts/src/modules/search/global-search.js
Hi @gtvj,
Would it be possible to have a look at this PR? It's makes a small change to how the hamburger menu and search buttons behave (requested by Simon). Currently, both the menu and search component can be open at the same time. This PR modifies the button behaviour so that if the hamburger menu is clicked when the search component is open, the search component will minimise, and vice versa. Thank you 👍
=> Fix hamburger menu and search button toggle behaviour

.platform.app.yaml, .platform/routes.yaml, .platform/services.yaml
We stopped using ES in the application a while ago, but we didn't want to play around with platform.sh config at the time, as we weren't entirely sure what the impact would be on other environments.
These changes were successfully applied to the `auth0-integration` environment, which appears to have worked safely, without impacting any other environments.
=> CHORE: Remove redundant elasticsearch service from platform.sh config

sass/includes/_header.scss, sass/includes/_login-status.scss
UN-231: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-231&assignee=5df0cc4447c6b30ec90c99de
Hi @sdwilkes,
This PR hides the login status above the header banner. I've also added a small fix for the navigation menu items (added some extra margin) as I noticed there wasn't enough space around the `li`'s for the focus styles (the 5px outline) to display fully (screenshots below). Thank you 👍 
Without extra margin:
With extra margin:
- [ x] Checked things thoroughly myself before handing over to you.
- [ x] Included the ticket number in the PR title to help us keep track of changes
- [ x] Ensured that my PR does not include any irrelevant commits.
- [ x] Waited for all CI jobs to pass before requesting a review. …
=> Header fixes (including UN-231)

.platform/routes.yaml
- https://national-archives.atlassian.net/browse/DF-54
Tweak platform.sh cache settings so that GTM conditionally renders successfully.
=> DF-54: Tweak platform.sh cache config to fix cookie consent

sass/includes/_promoted-item.scss
This PR amends the margin rule for featured links (called `promoted-item` in the codebase) to resolve a spacing issue (screenshots below). Would it be possible to merge if all's okay? Thank you 👍 
Without margin adjustment:
With margin adjustment:
=> Adjust spacing rule for featured links

templates/collections/time_period_explorer_page.html, templates/collections/topic_explorer_page.html
- Load missing wagtailimages_tags in topic_explorer_page.html
- Unrelated: Remove duplicate loading of wagtailcore_tags in time_period_explorer_page.html
- https://sentry.io/organizations/the-national-archives/issues/3440592190/
=> Fix: TemplateSyntaxError: Invalid block tag on line 19: 'image', expected 'elif', 'else' or 'endif' 

etna/collections/tests/test_models.py, templates/includes/card-group-record-summary-no-image.html, templates/includes/card-group-record-summary.html
Changes include:
- Swapping the order of catalogue data for Wagtail supplied data
- Swapping record.title (which does not seem to return anything) for
record.description and truncating it to different word lengths
depending on whether it is before or after the image
- Using striptags to prevent the XML from appearing
=> Highlight card changes

etna/media/templates/wagtailmedia/chooser/chooser.html, templates/search/blocks/search_landing_hero.html, templates/search/catalogue_search_long_filter_chooser.html, templates/search/website_search.html
This has been requested by the metrics team. Whereas I've ensured all
IDs are prefixed with `analytics-` I have not changed any existing IDs
since these might be included in existing reports etc.
=> Add IDs to all forms that didn't have one

etna/collections/tests/test_models.py, sass/includes/_card-groups.scss, templates/includes/card-group-record-summary-no-image.html, templates/includes/card-group-record-summary.html
Related ticket(s): https://national-archives.atlassian.net/browse/DF-106?atlOrigin=eyJpIjoiZWQzNTIyOTMwNDQ3NDQ3NTlhODdmNjRjNzczNWY3NTMiLCJwIjoiaiJ9
Remove catalogue description from below the thumbnail. As requested in the Jira ticket (see comment from SW on 25 July.
On highlights pages there should be no text below thumbnails and, where there is no image, there should only be a title.
=> Remove card group record summary body

sass/includes/_breadcrumb.scss, templates/includes/breadcrumb.html
https://national-archives.atlassian.net/browse/UN-266
I have added in the required functionality as per the ticket
Please explorer the collection and observe the behaviour of the breadcrumbs. On Mobile you should only see 'Home ' > 'Selected page'
=> breadcrumb display and functionality

etna/ciim/client.py, etna/ciim/constants.py, etna/ciim/tests/test_client.py, etna/search/views.py, templates/search/blocks/search_filters.html
- https://national-archives.atlassian.net/browse/DF-333
- Added level field to use OR operator when performing search for Level filter.
- Level filter is hidden for “Records at other UK archives”
Under catalogue search select more than one level - example Item+Piece
=> DF-333:Added level to use OR operator

config/settings/base.py
Default DEBUG must be False, otherwise if this env variable is removed, user will get to view error log.
https://github.com/nationalarchives/ds-wagtail/pull/460/files#diff-f7a16228131ae92457c22657bb33458207a7578b8cdb6ff796153916fa67a22dL26
=> CHORE: Set default DEBUG to False

etna/insights/blocks.py, etna/insights/models.py
https://national-archives.atlassian.net/browse/UN-303
Made it so private pages do not get displayed in the insights index page, this can be used to allow for a "live" review of the page by sending the link and password to someone, but will not show to the public on the index page.
They will still be selectable on the page chooser, but when published/saved it will remove itself. I'd like to make it throw an error if they try to publish a draft/private page but not sure how to do this currently.
Set an insights page to "private" in the Wagtail CMS and see if it appears on the index page.
=> UN-303 private insights hidden from index

poetry.lock, pyproject.toml
https://national-archives.atlassian.net/browse/DF-358 django-upgrade
https://national-archives.atlassian.net/browse/DF-404 search-filters
Restores django=4.0 to django=~3.2
code changes applied in 4.0 compiled for 3.2.15 without errors
from django.urls import re_path
from django.utils.translation import gettext_lazy as _
Apply Level search filter for Online records - results shown in same bucket.
Apply Search text on Online records - results shown in same bucket.
Admin Record Chooser
Admin Site Menu messages
=> DF-358-django-upgrade: Revert due to DF-404-search-filters-issue

.platform/routes.yaml
https://national-archives.atlassian.net/browse/UN-350
Turning server http cache off, to see if wagtail admin changes are reflected immediately to end user
Check if wagtail admin changes are reflected immediately to end user
=> UN-350:disable cache

.platform/routes.yaml
https://national-archives.atlassian.net/browse/UN-350
Turning server http cache on (after turning it off), to see if wagtail admin changes are reflected immediately to end user
Check if wagtail admin changes are reflected immediately to end user
=> UN-350:enable cache

.platform/routes.yaml
https://national-archives.atlassian.net/browse/UN-350
Turning server http cache on/off via `env.HTTP_CACHE_ENABLED`, to see if wagtail admin changes are reflected immediately to end user
Check if wagtail admin changes are reflected immediately to end user
=> UN-350:added HTTP_CACHE_ENABLED env to enable/disable cache

.platform/routes.yaml
https://national-archives.atlassian.net/browse/UN-350
Turning server http cache on/off via env.HTTP_CACHE_ENABLED, to see if wagtail admin changes are reflected immediately to end user
Check if wagtail admin changes are reflected immediately to end user
=> UN-350:update HTTP_CACHE_ENABLED env to enable/disable cache

etna/collections/models.py, templates/collections/time_period_explorer_page.html, templates/collections/topic_explorer_page.html
(https://national-archives.atlassian.net/browse/UN-367)
Moved the position of the featured insight to be above the collection.
Check that featured insight is above "body" in the CMS, and in the HTML that the featured insight highlight is above the collection highlights. This needs to be checked in both the topic explorer, and time period explorer pages.
=> UN-367 Changed layout of explorer pages' featured insight

sass/includes/search/_long-filters.scss, scripts/src/modules/search/search-long-filters.js
https://national-archives.atlassian.net/browse/DF-373
Long Filters page will now display and Intro paragraph depending on searching in 'Collections' or 'Held by'
Go to Long Filter page for collections and for held by, confirm that the intro paragraph is correct
=> Df 373 add copy to long filters pages

scripts/src/insights.js
(https://national-archives.atlassian.net/browse/UN-372)
As in the title
Check that data-card-position is on the text link (as well as image link) of Insights cards at the bottom of an Insights page.
=> UN-372 - Added feature to cards on Insights page, as it was only on Insights Index

templates/collections/time_period_explorer_page.html, templates/collections/topic_explorer_page.html, templates/home/home_page.html, templates/insights/insights_index_page.html
https://national-archives.atlassian.net/browse/UN-432
<- Use teaser images instead of hero images in the templates with featured_insight relationship  ->
=> Changing to teaser images for the insight_featured relationship

templates/search/blocks/catalogue_search_buckets.html
https://national-archives.atlassian.net/browse/DF-352
Fixes : When you change a bucket in the drop down, it doesn’t keep your original search term, it switches to a  * wildcard search.
=> DF-352:Keep search term in dropdown when changing buckets

etna/search/views.py
https://national-archives.atlassian.net/browse/DF-334
- Updates customMetric2 to reflect selected filters count across sum of all selected filter values
- provisions the same count as a context var to be used for Mobile UI
Verify count in customMetric2 of datalayer for selected filter count in desktop view.
=> DF-334: datalayer filter count update

etna/ciim/constants.py, etna/search/templatetags/search_tags.py, etna/search/tests/test_search_tags.py, templates/search/blocks/search_results__list-card--grid.html, templates/search/blocks/search_results__list-card.html
https://national-archives.atlassian.net/browse/DF-457
- Fixed missing divs
- Removed problematic alt value, added alt without value to grid template
- Restore and Update condition for teaser image
- To look into further to refactor constants using bucket keys : created DF-470 (as mentioned in the DF-457 )to address this bit.
ALT value should not appear for any search results.
=> DF-457:Alt tag amend

scripts/src/modules/search/mobile-filter-expander-enhanced.js
https://national-archives.atlassian.net/browse/DF-502
Changing the value of data-link-type on mobile search
Conduct a search, any search.
Press F12, or right-click and Inspect, and change to Mobile display using the Responsive design tool.
Right-click the Filter button and select Inspect - does the data-link-type = ”mobile button”?
=> DF-502 : update to data-link-type for mobile search

templates/404.html, templates/500.html, templates/503.html
(https://national-archives.atlassian.net/browse/UN-466)
Added correct font to the 404, 500, and 503 error pages.
Also added page icons
Go to localhost:8000/404, localhost:8000/500, localhost:8000/503 and see that font is different to the one currently shown on develop/beta.
=> UN 466: Update font on the error pages

etna/insights/migrations/0036_migrate_insights_body_content_to_content_sections.py
We've noticed on other PRs that tests can fail due to app migrations running in an unpredictable order.
Previously, the data migration in the `insights` app would always run BEFORE the migration to rename the `PageRevision` model in wagtail - So, it was fine to carry on using that model name. However, when migration changes cause Django to run the wagtail migration BEFORE reaching ours, the model name is no longer valid, and we see the errors in CI again.
Because Django migrations do not have a way to specify "Run this migration BEFORE these other ones", but do have a way to specify "Run this migration AFTER these other ones", the safer/more consistant fix is to make sure our data migration runs AFTER the rename ones, and use the updates `Revision` model name so that the error goes away.
=> CHORE: Fix Reference to `PageRevision` in data migration

etna/records/field_labels.py, etna/records/models.py, etna/records/tests/test_models.py, templates/articles/blocks/featured_record.html, templates/articles/blocks/featured_records.html, templates/includes/card-group-record-summary-no-image.html, templates/includes/card-group-record-summary.html, templates/includes/records/hierarchy-full-item.html, templates/includes/records/hierarchy-global.html, templates/includes/records/record-details.html, templates/includes/records/record-related-records.html, templates/includes/records/record-series-panel.html, templates/includes/records/record-title.html
https://national-archives.atlassian.net/browse/DF-513
Some record attributes are inconsistent with the API response attribute. This change is to make them consistent and apply them to the templates. 
**Making them consistent enables easier debug and maintenance.**
- created_date
- access_condition
- summary_title
- delivery_option
As mentioned in the ticket.
- check PR merge tile begins with ticket number Ex `DF-XXX: …
=> DF-513:Make record attributes consistent with API response

scripts/src/modules/search/mobile-filter-expander-enhanced.js
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/boards/76?selectedIssue=DF-556
- Removes aria-label so SR users hear the button content (including number of active filters)
- Always show number of active filters (even if its 0) for users benefit
- Perform search on mobile view
- See that the filters button text is updated to 'Show filters' and now always shows number of active filters
- Inspect filters button to confirm the aria-label has been removed
- Test with Voiceover (or another SR) to check the button content & number of active filters are read aloud. Make sure the current state of the button is still announced correctly.
- [  ] Added/updated tests and documentation where relevant. - N/A
1. Use the `Squash and merge` option to keep the target branch's …
=> [DF-556] Filter number indicator does not appear until after opening the filter dropdown

etna/articles/models.py, sass/includes/_card-grid.scss, sass/includes/_transcription.scss, templates/articles/record_article_page.html, templates/includes/image_gallery.html, templates/includes/record-matters.html, templates/includes/record-revealed.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-496
- Teaser images are now square instead of rectangular.
- non-preview images are now original size, although if displayed with text they're restricted to the max-width of the div to create as consistent sizing of content as possible.
- Logic added to allow for images to be added without transcriptions / translations. This displays the images as full-width / height (as much as possible).
- view images and transcirptions text now shows as "views images" if no transcriptions and translations are added.
- "Read more" in the record revealed only shows if is over 300 characters. Likewise truncation happens at this point.
- Fix the layout of the featured article button so it uses the correct colour scheme.
- "You maybe interested" …
=> UN-496: Record revealed content changes

etna/articles/models.py
Ticket URL: https://national-archives.atlassian.net/browse/UN-501
Removed `collapsed` class on the MultiFieldPanel on required articles pages.
Enter admin panel, edit an articles page - see if the Content Warning options section is un-collapsed/opened by default.
=> UN-501: Remove "collapsed" by default ContentWarningMixin

sass/includes/search/_search-sort-view.scss, templates/search/blocks/catalogue_search_buckets.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-563
Small bug fix to move the select box width change to the smaller breakpoint - currently it is applied at desktop and causing mis-alignment of the select box.
- Open catalogue search results page
- Check desktop and see the sort by filters are aligned correctly on the right-hand side
- Check mobile / tablet and see the sort by filters re-aligned correctly to full-width
Follow …
=> [DF-563] Bug fix: Select box width

.platform.app.yaml, templates/base-images.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-481
Fixes `css/libraries/tna-toolkit.0.0.1.css.map' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage` on Django Upgrade; but also commented as Kong open beta API does not support media currently.
At the time of deployment to server.
=> UN-481:Fix-commented tna-toolkit.0.0.1.css to allow upgrade to Django4.1.X;Kong open beta API does not support media.

templates/search/blocks/search_sort_and_view_options.html
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/boards/76?selectedIssue=DF-583
Moves hidden form input fields (and error fields) outside of the `<ul>` element to avoid validation issues. 
- Visit search results page
- View page source
- Copy page code into w3 validator (https://validator.w3.org/)
- Run validator check
- See that the `Element 'input' not allowed as child of element 'ul'` validation issue is no longer present
**IMPORTANT:** I'm not 100% sure of the best way to test the way the errors display for the 'sort by' fields, so I'd appreciate if this could be tested by someone who knows this better than I do! Thank you! 
Follow …
=> [DF-583] Element 'input' not allowed as child of element 'ul'

templates/search/blocks/search_filters.html, templates/search/blocks/search_sort_and_view_options.html
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/boards/76?selectedIssue=DF-584
- Adds unique ID for 'sort by' forms to differentiate mobile & desktop forms
- This also updates the ID for the search results sort by GTM tracking so this will also need double checking to make sure it's still pulling through the correct values
- Navigate to search results
- On desktop, inspect 'sort by' form and see that the ID has been updated to identify desktop form `id="catalogue-sort-form-desktop"`
- On mobile, inspect 'sort by' form and see that the ID has been updated to identify mobile form `id="catalogue-sort-form-mobile"`
- Test GTM tracking to make sure this is still pulling through as expected (one for Beth/Helen)
Follow …
=> [584] Duplicate ID catalogue-sort-form

templates/search/blocks/search_pagination.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-586
Replaces `<` and `>` characters with HTML character codes to avoid validation errors
Check pagination template and see that the previous/next arrows have been replaced with HTML characters
=> [DF-586] Unescaped < and > characters

templates/search/blocks/search_pagination.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-586
An additional update to remove SR-only text on pagination labels. Each label already has an aria-label which takes precedence, so the SR-only text was redundant.
- Check the template and see the SR-only text has been removed
- Test search result pagination with screenreader to confirm that aria-label is read aloud and label text is ignored
=> [DF-586] Remove SR-only text

etna/records/fields.py
This issue was picked up in another piece of work: https://github.com/nationalarchives/ds-wagtail/pull/731/files/5a8225228352f4314cc6b0ffa4943661c12fe815#diff-30c282345332260c1c59165b3100c5301fb4efe3e7902eaecff52036a2289d19
You should be able to successfully choose a record for an image in Wagtail, save the image, then successfully edit the image again.
=> Fix: RecordChoiceField.validate() and LazyRecord.__init__() still using old 'Manager' to access api

sass/includes/_explore-intro.scss, sass/includes/_transcription.scss, templates/includes/image_gallery.html, templates/includes/record-revealed.html
Ticket URL: : https://national-archives.atlassian.net/browse/UN-496
Changes requested: https://national-archives.atlassian.net/browse/UN-496?focusedCommentId=42916
Load a record article page with the transcirption gallery, images are now the original sizes. After speaking with the content team they will take ownership of sizes / layout changes and want the abillity to use large images.
=> Un 211 continued editor feedback

etna/core/static/admin/js/inputLengthIndicators.js, etna/core/static/css/wagtail-overrides.css, etna/core/wagtail_hooks.py
Ticket URL: https://national-archives.atlassian.net/browse/UN-494
Adds a Draftail-like character count to any plain text input with a `maxlength` attribute (as long as it's present when the form is initially rendered).
This means that behaviour will be a little inconsistent between inputs present in newly added blocks VS blocks that were present on load... But, I can't find a nice way to cater for those. Let's just see how we get on with this lightweight version and we can complicate things further later if necessary?
I have also snuck some style overrides to help the legibility of Draftail character counts when help text is long enough to clash.
Edit any page in the Wagtail admin and open the **Promote** tab. You should see a character count when editing the following fields:
- Slug
- …
=> UN-494: Show character count for `teaser_text`

etna/records/models.py, etna/records/tests/test_models.py, templates/search/blocks/search_results__list-card--grid.html, templates/search/blocks/search_results__list-card.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-596
We rightly strip HTML from record descriptions in listings, where links and other HTML entities cause unnecessary complication for users. However, in certain circumstances, we want to display the full value as retrieved from the API, with any links etc left in-tact.
This PR changes the `description` property available for records, so that it no longer strips HTML. A new `listing_description` property is added to make the value available with the same treatment.
As per the example in the ticket, head to http://0.0.0.0:8000/catalogue/id/C18099/ locally and look out for the 'Description' value there. It should now include the link from the original value.
However, when you see the description in search results, it'll still be …
=> DF-596: Prevent stripping of HTML from record descriptions in detail view

etna/core/models/mixins.py
Ticket URL: https://national-archives.atlassian.net/browse/UN-491
Go into the admin, edit an article page, and apply the "Mark this page as 'new' when published". Publish the page and check that the "NEW" label is being applied to the card.
Now, go and edit the same page again in Wagtail and republish it. The "NEW" label should still be applied to the card when you go and look again.
=> UN-491: New label fixes

sass/includes/_explore-intro.scss, sass/includes/_generic-intro.scss, templates/articles/article_index_page.html, templates/articles/article_page.html, templates/collections/explorer_index_page.html, templates/collections/highlight_gallery_page.html, templates/collections/time_period_explorer_index_page.html, templates/collections/time_period_explorer_page.html, templates/collections/topic_explorer_index_page.html, templates/collections/topic_explorer_page.html, templates/generic_pages/general_page.html, templates/home/home_page.html, templates/includes/generic-intro.html, templates/includes/record-revealed.html, templates/records/record_disambiguation_page.html
Ticket URL: [here](https://national-archives.atlassian.net/browse/UN-514)
This change increases the intro-text of all page types to be `1.3125em` which is approx 21px as requested in the ticket. 
affected templates; 
```
./templates/articles/article_page.html
./templates/articles/article_index_page.html
./templates/collections/time_period_explorer_index_page.html
./templates/collections/topic_explorer_index_page.html
./templates/collections/explorer_index_page.html
./templates/collections/topic_explorer_page.html
./templates/collections/time_period_explorer_page.html
./templates/collections/highlight_gallery_page.html
./templates/generic_pages/general_page.html
./templates/home/home_page.html
./templates/records/record_disambiguation_page.html
./templates/includes/record-revealed.html
``` …
=> Un 514 short description

sass/includes/_explore-intro.scss, templates/includes/record-revealed.html
Ticket URL: [here](https://national-archives.atlassian.net/browse/UN-496?focusedCommentId=44225)
Increases the breakpoint of hiding the `teaser_image` from mobile -> tablet to reduce aliasing seen by users
This can be seen at any RecordArticlePage, such as [this](http://0.0.0.0:8000/explore-the-collection/a-letter-by-the-women-workers-at-fords-of-dagenham/)
=> Hide teaser image at tablet viewport

etna/ciim/constants.py, etna/search/tests/test_views.py
Ticket URL: https://national-archives.atlassian.net/browse/DF-617
As the way the Highlights are created the current implementation in the Website results tab is broken i.e. the links go to 404 pages and thumbnail images no longer exist. 
The task is to remove (or hide) the Highlights bucket until we can properly include the descriptions and images from the Highlights.
Head to this URL locally: https://localhost:8000/search/website/?q=test
The 'Highlights' bucket should no longer be visible.
=> DF-617: Remove 'Highlights' from WEBSITE_BUCKETS

templates/search/blocks/search_results.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-618
Fix paginator count to show in search results.
- Navigate to search bucket - Ex Catalogue results -> Records at National Archives
- View Showing 1-20 (of `missing count should show here`) result for "*" in "Records at The National Archives"
=> DF-618:Fix missing search counts

etna/collections/models.py, templates/collections/time_period_explorer_page.html, templates/collections/topic_explorer_page.html, templates/includes/related-articles-highlight-cards.html
Ticket URL: [here](https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-512)
A quick change to use related_record_articles instead of related_articles for TimePeriod and Topic ExplorerPages.
From review, this MR's purpose has extended slightly to cover some formatting issues, which uncovered some issues from rebasing develop.
Check both of those page types, see that the section titled "records revealed" is populated by RecordArticlePages.
=> fix; use related_record_articles instead of related_articles

etna/collections/models.py, sass/etna.scss, sass/includes/_card-grid.scss, sass/includes/_highlight-intro.scss, sass/includes/_related-highlight-cards.scss, sass/includes/_variables.scss, templates/collections/time_period_explorer_page.html, templates/collections/topic_explorer_page.html, templates/includes/article-spotlight.html, templates/includes/highlight-intro.html, templates/includes/related-highlight-cards.html
Ticket URL: [here](https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-511)
These changes add a hero, and the cards seen bellow. 
Please note that I've taken a fair amount of liberty with the layout / colours for the hero, as were positioning the text offset centre I've tried to preserve this as much as possible instead of just using the mobile view basically for anything lower than 1440px width. I also found that without the hero intro colour being darker than the page it wasn't particularly clear what was happening for tablet+ sized screen widths. Please do let me know if you think this could be done better.
Also note, the lettering of the titles for the hero and cards is wrong, we do not have `Supra Sans` available in the code …
=> un-511 hero and gallery cards

etna/images/models.py
Ticket URL: https://national-archives.atlassian.net/browse/DF-550
We are not indexing 'title', 'collection' and other default fields when indexing images. Hence why we are seeing such poor results when searching.
Run `python manage.py update_index` locally after pulling these changes. You should then see far better search results in Wagtail's search view.
=> UN-550: Fix: Poor image search results in Wagtail

sass/includes/_featured-record.scss, templates/articles/blocks/featured_record.html
Ticket URL: [paste URL here](https://national-archives.atlassian.net/browse/UN-509)
Changes the label "Visit the record" -> "View in the catalogue" and adds some additional right padding at large breakpoint to account for the longer button
Add a featured record to the story template, and check that the button text shows "View in the catalogue"
=> Visit the record -> View in the catalogue

sass/includes/_featured-records.scss
Ticket URL: https://national-archives.atlassian.net/browse/UN-378
Added `margin-bottom` to the `featured-records` element in the SASS.
Go on a Stories/Article page, add a featured records block to the page.
I would suggest William Cuffey, an example here:
Then view the page and ensure there is a gap between the featured-records component, and the content below it
=> UN-378: Spacing between Featured Records and Image components

etna/search/forms.py, etna/search/views.py
Ticket URL: https://national-archives.atlassian.net/browse/DF-320
FeaturedSearchView.get_buckets() should only add counts and hits to bucket data if the API has been called - which isn't the case when the form submission is invalid.
We've also changed our minds on applying a minimum length to the query, so this PR has also removed that validation (the first issue was important to resolve though, as the form could always change in future)
Resolves: https://the-national-archives.sentry.io/issues/4079397086
Do a search locally for "a" - you should no longer see a Django error page due to the invalid form
Follow [docs\infra\environments.md](https://nationalarchives.github. …
=> DF-320: Fix FeaturedSearchView when search form is invalid

.github/workflows/cd.yml, .github/workflows/main.yml
I'm hoping this will reduce the likelihood of bad cache hits, which appear to be causing workflows to fail sporadically.
=> CHORE: Tweak venv dependency cache keys in GitHub workflows

templates/collections/time_period_explorer_page.html
Ticket URL: ticket [here](https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-201)
This change is just removing the feature flag left over from rebasing this one to many times and becoming blind to this. Screenshot of page after removing the flag; 
=> Fix templates after rebase

templates/collections/topic_explorer_page.html
Ticket URL: [here](https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-201)
Yet again fixing merge conflicts caused by too many changes over the same templates. 
Load a TopicExplorerPage using staging data (local link [here](http://0.0.0.0:8000/explore-the-collection/explore-by-topic/british-state-and-citizens/).
=> Fix topic explorer page template

scripts/src/catalogue-search.js, scripts/src/modules/analytics/search/search_filters_tracking.js
Ticket URL: https://national-archives.atlassian.net/browse/DF-607
The JS is developed in such a way that assumes the list of selected filters is always rendered, so I've refactored slightly so that the JS only runs when everything is present.
There was also some weird/unnecessary wrapping of functions here, which I've tried to simplify. I've also tried to make the remaining function names a bit more obvious.
=> DF-607: Fix JS error on search results page

etna/search/forms.py, etna/search/tests/fixtures/catalogue_search_with_multiple_filters.json, etna/search/tests/test_views.py, etna/search/views.py
Ticket URL: https://national-archives.atlassian.net/browse/DF-396
Check out the following URL in develop: https://develop-sr3snxi-rasrzs7pi6sd4.uk-1.platformsh.site/search/catalogue/?collection=DEFE&collection=HW&collection=RGO&level=Piece&closure=Open+Document%2C+Open+Description&q=test+search+term&group=tna
Notice how the **Collections** filter options for 'DEFE' and 'RGO' have disappeared, despite being applied?
Now check out the same URL locally: http://localhost:8000/search/catalogue/?collection=DEFE&collection=HW&collection=RGO&level=Piece&closure=Open+Document%2C+Open+Description&q=test+search+term&group=tna
The missing filter options should now appear with with a '(0)' count in brackets to indicate they have no matches when combined with the other active filters.
Follow …
=> DF-396: Fix disappearing selected filters when other applied filters make them redundant

templates/includes/image_gallery.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-542
Moved the </a> tag inside the if statement above it. This prevents the </a> from randomly displaying, if the if statement isn't met. It will then display with the <a> which it is supposed to close.
Check that the </a> is not being randomly displayed in the HTML.
=> UN-542: Stray </a> tag 

templates/includes/record-matters.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-544
Removed `href` on `<button>` element on record revealed page
Ensure that the href has been removed from the button element
=> UN-544: Remove href attribute on <button> element

templates/articles/article_index_page.html, templates/collections/highlight_gallery_page.html, templates/includes/article-spotlight.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-535
Added an `sr-only` span to the link, and added the text "about {{ insert_title_variable_here }}" to add context to the links for screen readers.
Navigate to a featured article spotlight (e.g. on stories index page) and check that the sr-only span has been added with the correct text.
=> UN-535: Spotlight article CTA text doesn't provide context

templates/includes/image_gallery.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-543
Removed empty `<p></p>` tags.
There will be some empty `<p>`s with ids. This is from the `rich_text` fields, and the editors putting in a blank line. Perhaps some editor guidance on why they shouldn't do this, or is there a way we can ensure there are no blank lines put in?
Check on record revealed pages that there are no empty `<p></p>`s.
=> UN-543: Remove empty/un-needed <p></p> tags

etna/search/forms.py, etna/search/templates/search/widgets/search-filter-checkbox-list.html, sass/includes/search/_search-filters.scss
Ticket URL: https://national-archives.atlassian.net/browse/DF-575
This PR adds a custom widget for use in search filters, allowing us to customise the template, and render an actual `<ol>` element with an `<li>` for each option.
I deliberately haven't gone to pains to ensure labels and checkboxes have custom BEM classes on too, as that feels like complication for complication's sake.
Check if the search filters are rendering okay for you here: 
http://localhost:8000/search/catalogue/
=> DF-575: Use list markup for search filters

scripts/src/modules/image-gallery.js
Ticket URL: Ticket [here](https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-564)
This updates the scroll behaviour when opening and closing the image gallery, it follows the position of the image gallery preview on close or the first element of the gallery upon open. 
Here's a quick video of the behaviour; 
=> un-564-record-revealed-interaction-update

.coveragerc, .github/workflows/main.yml
This version adds a coverage report to CI. This is helpful for seeing where our test gaps are, but EVEN MORE helpful would be enabling a GitHub App like Codecov.io and uploading coverage reports to that. This will give you a very obvious / visual indication of pull requests about how the coverage has changed, and where the gaps are.
=> CHORE: Measure code coverage in CI test runs

templates/search/website_search.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-587
This removes the parent `<form>` element which contained another `<form>` child element (./blocks/search_results_hero.html) - this was throwing a validation error as it isn't valid HTML to contain a form inside another form.   The parent form did not include any form input fields inside it nor did it have any other indication it was needed (from what I could tell), so I have removed it. This is also now consistent with the `catalogue_search.html` template.
I felt a little uncertain removing this form as it seemed it could be required for analytics in some way (?) but I'm really not sure what I would need to test to make sure it hasn't broken anything as I'm not very familiar with the existing code or why the form was added …
=> [DF-587] Remove extra (unneeded?) <form> element

templates/includes/image_gallery.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-563
Added sr-only span to provide context on the "close" button. This includes an if statement to include "transcripts" if there are transcripts (same as the open button).
Check the HTML on open/close button on the record revealed image gallery.
=> UN-563: Close button does not provide sufficient context

sass/includes/_featured-article.scss, sass/includes/_footer.scss, sass/includes/_transcription.scss
Ticket URLs: 
https://national-archives.atlassian.net/browse/UN-534
https://national-archives.atlassian.net/browse/UN-548
Adds some transparent borders to key content areas - the transparent border appears as a solid border in high contrast mode and provides clear boundaries around sections of content so the layout is easier to distinguish for high contrast users.
1. Open stories or a record revealed page locally
3. Open devtools, click the 3 dots and open More Tools > Rendering:
3. Change the forced-colors setting to 'forced-colors: active' to emulate high contrast mode - you can set this to 'light' or 'dark' theme by changing 'prefers-color-theme' setting as well:
4. Review page and see that the image gallery and featured content components have visible borders around the content. …
=> [UN-534] [UN-548] Add boundary borders to featured content areas for high contrast mode

templates/includes/image_gallery.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-546
Remove aria-labelledby attribute from tablist as it was pointing to an element that didn't exist and doesn't add any value.
1. Open record revealed locally
2. Inspect the transcript tabs and see the tablist no longer has an `aria-labelledby` attribute
=> [UN-546] Remove unused aria-labelledby attribute

templates/articles/article_index_page.html, templates/includes/card-group-secondary-nav.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-536
Adds an extra ID based on the card forloop, to ensure the second group of cards have unique IDs and don't conflict with the featured cards.
It might make sense to remove these` aria-labelledby` attributes in future, as I'm not sure they are necessary - but no harm in them being there right now. This fixes the validation errors for now.
1. Review stories landing page locally
2. Inspect code and see that the ID and aria-labelledby attributes are different for featured cards vs 'all stories' cards.
=> [UN-536] Multiple duplicate IDs for article descriptions

etna/records/tests/test_blocks.py, templates/articles/blocks/featured_record.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-560
Changed sr-only text on CTA label to use the title of the "record" component, instead of the actual record title.
=> UN-560: View the record CTA sr-only repeats the name of the full record which is very verbose

templates/includes/image_gallery.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-547
Removes `tabindex="0"` from the image counter element as this isn't part of the interactive tab content and so has no need to be focusable.
1. Review record revealed page
2. Tab through page content with tab key
3. Notice that the image counter content (Image 1/2) is not focusable with the keyboard
=> [UN-547] Record revealed - only interactive elements should be focusable

templates/includes/record-matters.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-551
Updated button text on the gallery
Check that the text has been updated
=> UN-551: "Read more" and "Read less" button label not descriptive

templates/articles/article_index_page.html, templates/includes/article-spotlight.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-556
Updated CTA links to show "Read about X"
Check anywhere the "featured story" is used and ensure that text is "read about (title)"
=> UN-556: Featured Story CTA label is not descriptive enough

sass/includes/_content-warning.scss
Ticket URL: N/A
I believe the colour was changed from some merge conflicts in a PR for UN-506, so I have re-added the new colour here.
Check that the colour of the content warning icon has changed
=> CHORE: Changed content warning colour to `color__grey-2`

templates/blocks/featured_record_article.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-470
As reported on the ticket, using the block results in a `TemplateSyntaxError` in the preview panel. Technically, the FE ticket should resolve this, but there's no good reason to leave it erroring in the meantime.
=> UN-470: Fix FeaturedRecordArticleBlock TemplateSyntaxError

templates/collections/highlight_gallery_page.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-654
Added the large link cards to the bottom of the Highlights Gallery page
Check a Highlights Gallery page that is tagged with a topic and time period. There should be two large link cards displaying the most relevant topic + time period.
=> UN-654: Add large link cards to HG page

etna/core/wagtail_hooks.py
I have made the side-bar on develop a dark green to fit in with the dark mode - this is so that the editors can tell the difference between develop and main.
Set `FEATURE_PLATFORM_ENVIRONMENT_TYPE = "development"` in your `local.py` and it will show you the styles that are meant for develop only.
=> CHORE: Update dark mode develop theme

etna/collections/models.py, etna/core/models/settings.py
Ticket URL: https://national-archives.atlassian.net/browse/UN-584
Sidestep a [known issue](https://github.com/wagtail/wagtail/issues/9391) in Wagtail by avoiding specifying `min_num` for `InlinePanel`s
=> Fix: Highlights re-ordering when saved for the first time

sass/includes/_jumplinks.scss
Ticket URL: https://national-archives.atlassian.net/browse/UN-627
Updates the sticky navigation heading to the correct font
=> Updating jump link heading style

templates/includes/image_gallery.html
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-565
Adds an s to image and transcription when there's more than 1 image within the image gallery
Locally http://localhost:8000/explore-the-collection/test/ and http://localhost:8000/explore-the-collection/printed-circular-produced-by-the-national-league-of-the-blind/ and avaliable with the staging data
=> UN-565: Adding pluralize to image/transcript text

etna/collections/models.py
Ticket URL: [paste URL here](https://national-archives.atlassian.net/browse/UN-566)
Set `contentGroup1` on Highlight Gallery to "Highlight Gallery"
Open the console on a Highlight Gallery page, type `dataLayer` and check the `contentGroup1`. It should say "Highlight Gallery".
=> UN-566: Set cG1 on Highlight Gallery

templates/includes/highlights-gallery.html
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-515
Adds required tracking data attributes to 'View record details' links for the highlight gallery component. 
Review highlight gallery locally and see that the link data attributes are pulling through the correct values.
=> [UN-515] Performance Metrics - FE requirement to highlight gallery

templates/search/blocks/search_filters.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-473
Removal of helper text under the date filters on search results.
Perfom a search, go to catalogue results, check that there is no helper text under the date filters.
=> DF-473-removal of helper text

sass/includes/_hero-image.scss, sass/includes/_highlight-gallery.scss
Ticket URL: https://national-archives.atlassian.net/browse/UN-678
Updated HG font colour to use color__grey-300
=> UN-678: Updated Highlight Gallery font colour

templates/blocks/featured_record_article.html
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-651
Adds tracking for featured record article component
Compare requirements against generated data attributes on the FE. 
Local testing link: http://localhost:8000/stories/alice-hawkins/#h2.when-did-working-women-get-the-vote 
Component to inspect for data attributes:
=> [UN-651] Tracking data attributes for featured record article

sass/includes/_archive-collections.scss, sass/includes/_archive-description.scss
[DF-695: Fix colour display issues on Archive level page](https://national-archives.atlassian.net/browse/DF-695?atlOrigin=eyJpIjoiNzM5YTgyM2UzZjQxNGM3NjljMGU2MjllYjQzZTc4MWMiLCJwIjoiaiJ9)
This is a task to fix some identified colour issues discovered on the Archive level details pages.
The background colour has been changed from dark grey to light grey. Borders have also been added to the boxes on these pages to help with visibility.
The reviewer should do a visual check of the page to ensure the page looks correct.
Contact panel:
Collections panel:
=> DF-695: Fix colour display issues on Archive level page

etna/articles/models.py, sass/includes/_card-groups.scss, sass/includes/related-article-cards.scss, templates/articles/article_index_page.html, templates/home/home_page.html, templates/includes/article-spotlight.html, templates/includes/card-group-secondary-nav.html, templates/includes/related-article-cards.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-677
Added `title_label` to `RecordArticlePage` and `ArticlePage` to pull through "RECORD REVEALED" or "THE STORY OF" in the front-end.
Check anywhere that "stories" or "record revealed" pages are used and see that "THE STORY OF" or "RECORD REVEALED" are being pulled through correctly depending on the page type.
=> UN-677: Article title label

sass/etna.scss, sass/includes/_card-groups.scss, sass/includes/_featured-article.scss, sass/includes/_featured-articles.scss, sass/includes/_related-highlight-cards.scss, templates/blocks/large_links_block.html, templates/collections/explorer_index_page.html, templates/includes/article-spotlight.html, templates/includes/related-highlight-cards.html
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-598&quickFilter=61&quickFilter=65
Updates the front end of collection explorer to use the new BE fields and match the latest designs.
Check the Collection Explorer landing page locally, add all the new fields and compare the latest FE with the designs.
=> [UN-598] Collection Explorer landing page (FE)

templates/includes/related_topic_timeline_cards.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-532
This PR adds required data attributes for performance metrics. It also updates the related_topic_timeline_cards.html template to be in line with the latest card design. 
I've created this new PR and closed the existing one (https://github.com/nationalarchives/ds-wagtail/pull/943) as that was outdated.
1. Review record article or highlight gallery page locally
2. Check the related topic/timeline cards are using the latest styles
3. Inspect the elements and see if the data attributes are displaying the expected values (cross-reference with ticket requirements)
Follow …
=> [UN-532] Performance Metrics - FE requirements for Large link cards component 

templates/articles/article_index_page.html, templates/articles/article_page.html, templates/articles/blocks/featured_collection.html, templates/collections/blocks/featured_articles.html, templates/collections/explorer_index_page.html, templates/collections/time_period_explorer_index_page.html, templates/collections/topic_explorer_index_page.html, templates/includes/card-group-secondary-nav.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-667
Updated `card-group-secondary-nav` to use `link_page` instead of `page` so that we can access `page`.
Updated tracking requirements to use `heading` or `page.title` as a fall-back if `heading` doesn't exist.
=> UN-667: `card-group-secondary-nav` analytics

templates/includes/card-group-secondary-nav.html, templates/includes/related-article-cards.html, templates/includes/related-articles-highlight-cards.html, templates/includes/related-highlight-cards.html
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-659
This resolves the accessibility issue flagged when links wrapping images do not have link text - this occurs when an image doesn't have an alt tag or relevant aria-label.
This PR updates card image links to make sure they either:
-  have an `aria-describedby` attribute to point to the card title (this is if the link is used for GTM tracking, to make sure we are tracking SR and keyboard users interactions too)
- hides the link from SR and keyboard users by adding `aria-hidden` and `tabindex="-1"` to remove it from the taborder. This is only if the image is decorative and not necessary for context or tracking requirements.
Check the individual card types to make sure …
=> [UN-659] Accessibility - update card image links

scripts/src/modules/analytics/record_tracking/image_gallery_tracking.js, scripts/src/record-article-page.js, templates/includes/image_gallery.html
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-684
Adds GTM data layer push for the Open and Close gallery button. Also adds tracking for the Transcript/Translation tabs inside the image gallery once opened.
1. Open record revealed page locally (e.g. http://localhost:8000/explore-the-collection/the-monteagle-letter/)
2. Open the image gallery
3. Click on the transcript and translate tabs
4. Open the dev console and check the datalayer to see if the correct GTM values have been pushed from each button click:
Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/env …
=> [UN-684] Image gallery tracking

scripts/src/modules/record-matter.js, templates/includes/record-matters.html
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-669
Adds tracking for:
1. Catalogue reference link
2. Expand/collapse button
3. Yellow buttons underneath body content
1. Check record revealed page locally (e.g. http://localhost:8000/explore-the-collection/the-monteagle-letter/)
2. Inspect elements (outlined above) for relevant data attributes and see the correct values pulling through
3. Check the datalayer after toggling expand/collapse button and see that the values for this button have been sent to the datalayer correctly
Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds- …
=> [UN-669] Record revealed body content performance metrics

etna/records/views/records.py
Ticket URL: https://national-archives.atlassian.net/browse/DF-701
Update page rendering for record details page to allow GTM scripts to be included when Accepting cookies.
- Accept cookies when connecting to Etna
- Navigate to a record details page Ex: http://127.0.0.1:8000/catalogue/id/C11184/
- Check html source that it includes `gtm-script.html`  and `gtm-no-script.html`
=> DF-701: Gtm for record details page

templates/includes/related-highlight-cards.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-693
Fixing mistake of having "Card image" where it should say "Card text"
=> UN-693: FIX "Card image" -> "Card text"

templates/articles/record_article_page.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-708
Added `|slice:":5"` to only display the first 5 cards.
Add a featured highlight gallery to a record revealed page and then see if up to 5 cards are being displayed
=> UN-708: Featured HG display up to 5 highlights

sass/includes/search/_long-filters.scss
Fixes colour contrast accessibility issue for refine filters block on long filters
Check long filters page and see that the background of the refine results block has been updated and there are no colour contrast issues.
Before:
After:
=> Update long filters refinement block colours

etna/search/forms.py
Ticket URL: https://national-archives.atlassian.net/browse/DF-688
Temporary update for Country filter label.
- Navigate to Record creators search bucket.
- Observe the country filter label should show as **Location**
=> DF-688:Update contry filter label

etna/search/tests/test_views.py, templates/search/catalogue_search.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-703
Removal of duplicate message
Perform a search, In the Catalogue tab the message 'Results for records held at The National Archives and other archives that match your search term.' should only appear once.
=> DF-703 : removal of duplicate message

etna/records/models.py, etna/records/templatetags/records_tags.py, etna/records/tests/test_models.py, etna/records/tests/test_templatetags.py, templates/includes/records/hierarchy-global.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-699
Added Archive link for the record details page
- Open a record details page http://127.0.0.1:8000/catalogue/id/C11184/
- Click on the "Archive" link in records details page Hierarchy 
- The Archive details page http://127.0.0.1:8000/catalogue/id/A13530124/ should show
=> DF-699:Add archive link to record detail hierarchy

etna/core/fields.py, etna/core/widgets.py, etna/search/templatetags/search_tags.py, etna/search/tests/test_search_tags.py, etna/search/tests/test_views.py, templates/search/blocks/search_filters.html, templates/search/blocks/search_results_hero.html, templates/search/blocks/search_sort_and_view_options.html, templates/search/includes/filter.html, templates/search/long_filter_options.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-698
Follow up to #1041 to address some issues that occur when filtering by covering date, which happened due to the 'to' and 'from' date fields not being excluded from the hidden fields at the bottom of the form.
I realised the previous template tag code was a little ropey while reviewing #991, so have also refactored that to make better use of built-in Django stuff. I've also gone and added an 'include' option for the `search_filters.html` template to use so that we don't have to remember to add more field name strings there every time we add new filters.
1. With this branch active, head to [this URL](http://127.0.0.1:8000/search/catalogue/?filter_keyword=kew&covering_date_from_0=&covering_date_from_1=&covering_date_from_2=&cov …
=> DF-698: Convert template filters to tags and simplify hidden input rendering

sass/includes/_promoted-pages.scss, templates/articles/blocks/promoted_pages.html, templates/articles/record_article_page.html
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-721
Adds an if statement to check if `featured_article` has been added to the page - if it has, add a cream bg to the 'blogs and podcasts' section - if not, don't add bg. 
Check a local record revealed page (e.g. /explore-the-collection/list-of-suffragettes-arrested-from-1906-1914/), add/remove featured article and blogs/podcasts components and make sure the cream bg is added or removed as appropriate. 
With featured article:
Without featured article:
Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/ …
=> [UN-721] Change to background shading on 'Blogs and Podcasts' media component

templates/search/blocks/search_filters.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-698
Update field label for Covering dates to show "Dates"
- Navigate to search - Record at the national archives bucket
- Observe label Dates show for covering dates.
=> DF-698:Update field label for Covering dates

templates/collections/explorer_index_page.html
Fixes a validation issue for the `<h2>` heading as it had the wrong `</h3>` closing tag.
Open Collection Explorer landing page locally and see that the `<h2>` has the correct closing tag.
=> [a11y] Add missing </h2> tag on Collection Explorer landing page

templates/includes/card-group-secondary-nav.html
Fix for secondary cards (e.g. /explore-the-collection/) to resolve issue of links without labels - specifically the images for each card.
- Check that aria-labelledby is returning the correct label
- Run an automated accessibility check on a page with secondary cards and make sure no errors are reported for links missing labels
=> [a11y] Add aria-labelledby for secondary card links

etna/core/fields.py
Ticket URL: https://national-archives.atlassian.net/browse/DF-737
Update error message for invalid date range - when from date is after to date
[Link ](http://127.0.0.1:8000/search/catalogue/?filter_keyword=kew&covering_date_from_0=&covering_date_from_1=df&covering_date_from_2=&covering_date_to_0=&covering_date_to_1=&covering_date_to_2=sad&collection=ADM&collection=AIR&level=Item&closure=Open+Document%2C+Open+Description&opening_start_date_0=aa&opening_start_date_1=&opening_start_date_2=&opening_end_date_0=&opening_end_date_1=&opening_end_date_2=ccc&q=london&sort_by=title&sort_order=asc&group=tna)to view updated message
Follow …
=> DF-737: Update error message for invalid dates

.github/workflows/main.yml, config/settings/test.py
Birdbath has been raising warnings in test output and occasionally causing CI to fail, as is the case on https://github.com/nationalarchives/ds-wagtail/pull/1082. 
This PR uninstalls the app completely when testing, so that it can't cause any issues.
=> CHORE: Remove birdbath from INSTALLED_APPS when testing

sass/includes/_card-groups.scss
Ticket URL: https://national-archives.atlassian.net/browse/UN-714
Adjusts the green 'new' label assigned to new stories/records in the secondary cards - makes sure the label doesn't drop below the title when the title is longer than 1 line.
Review /explore-the-collection/ locally, check a secondary card with a long title and see that the 'new' label stays on the same line as the title and doesn't drop to a new line. 
Before: 
After:
=> [UN-714] Fix position of 'new' label for secondary card links and adjust padding

etna/core/fields.py
Ticket URL: https://national-archives.atlassian.net/browse/DF-739
Update invalid date message
[local url with invalid date criteria](http://127.0.0.1:8000/search/catalogue/?filter_keyword=&covering_date_from_0=&covering_date_from_1=&covering_date_from_2=sad&covering_date_to_0=&covering_date_to_1=sad&covering_date_to_2=&opening_start_date_0=ss&opening_start_date_1=&opening_start_date_2=1999&opening_end_date_0=&opening_end_date_1=ss&opening_end_date_2=1998&q=&sort_by=&sort_order=asc&group=tna) The error message should read - **Entered date must be a real date, for example 23 9 2017.**
Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra …
=> DF-739:Update invalid date message

docs/features/feedback-mechanism.md, etna/feedback/forms.py, etna/feedback/templates/feedback/includes/prompt.html, etna/feedback/templates/feedback/success.html, etna/feedback/tests/test_views.py, etna/feedback/urls.py, etna/feedback/views.py, sass/includes/_buttons.scss, sass/includes/_feedback.scss
Ticket URL:  https://national-archives.atlassian.net/browse/DF-726
We want users to be able to add a supporting comment to their feedback  even when Javascript is disabled. The nicest way I can think to do this is by adding the comment form to the 'success' page that you are redirected to after giving feedback.
Tracking opportunities here are limited, so I feel the best I can do is redirect to a separate 'success' URL for after the comment is successfully processed from here.
=> DF-726: Allow no-js users to add comments to feedback (BE)

sass/includes/_breadcrumb.scss
Ticket URL: [UN 748](https://national-archives.atlassian.net/browse/UN-748)
Fixed the issue where additional chevrons were appearing on mobile in the breadcrumbs
Resize the viewport to mobile width
[Page to test](http://127.0.0.1:8000/explore-the-collection/explore-by-time-period/early-20th-century/edwardian-textile-designs/)
=> UN 748 breadcrumb cheveron displaying multiple times

templates/base.html
Ticket URL: [UN-756](https://national-archives.atlassian.net/browse/UN-756)
Added meta tag to ignore numbers for mobile devices
Can be tested on mobile devices with this [link](http://127.0.0.1:8000/explore-the-collection/explore-by-time-period/medieval/)
[UN-756]: https://national-archives.atlassian.net/browse/UN-756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UN-756 Added meta tag to ignore telephone format numbers

etna/articles/models.py, etna/collections/models.py
Ticket URL: [UN-476]
Updated contentGroup1 to match required naming for pages
Open a page type that has been changed, press F12 and enter the console. Type `dataLayer` and then open the result. It should then say "Explore the collection" in contentGroup1
[UN-476]: https://national-archives.atlassian.net/browse/UN-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UN-476: contentGroup1 naming for pages under Explore the collection

etna/feedback/templates/feedback/includes/prompt.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-754
The 'Submit' and 'Close' buttons are currently implemented as `button` elements, both of which have the `submit` type value, so interacting with either results in form submission. This PR changes removes that attribute from the 'Close' option and adds some custom JS to handle hiding of the form and displaying of the success messaging without submitting comment text.
=> DF-754: Do not submit feedback comments on form close

etna/core/wagtail_hooks.py
Ticket URL: https://national-archives.atlassian.net/browse/UN-735
The RichText link tool wasn't functioning properly on image and media editing pages (e.g. http://localhost:8000/admin/media/edit/10/). This is a fix to enable those to work properly.
I inserted the extra JavaScript that the normal page edit view has, but was missing from the image and media views. This then enables those admin pages to use the RichText link editor without crashing.
Go to http://localhost:8000/admin/media/edit/10/ and try to add an in-text link to the description or transcript field.
=> UN-735: RichText fields crashing on image and media edit views

sass/includes/_breadcrumb.scss
Ticket URL: [UN-784](https://national-archives.atlassian.net/browse/UN-784)
Added a 100% width to fix the UI show the background colour fills the page
[Local page to test](http://127.0.0.1:8000/admin/pages/260/edit/preview/?mode=)
[UN-784]: https://national-archives.atlassian.net/browse/UN-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UN-784 Made breadcrumbs on focused articles 100% width to fill background

templates/articles/focused_article_page.html
Ticket URL: [UN-783]
Removed the HTML for the publication date from the Focused Article page
Open a Focused Article page and see that there is no more publication date
[UN-783]: https://national-archives.atlassian.net/browse/UN-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UN-783: Remove publication date from Focused Article

etna/core/models/basepage.py, templates/search/blocks/native_website_result--grid.html, templates/search/blocks/native_website_result.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-749
You shouldn't see the 'Published' date appear next to search results any longer, because all page types that appear in search results currently are considered 'evergreen' (not 'ephemeral').
=> DF-749: Only show publish dates for ephemeral pages in search results

templates/articles/focused_article_page.html
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-786
As per title of PR :)
Review focused article page locally and see there is no dotted border at the bottom of the page.
Ensure related articles still show as expected, without dotted top border.
=> [UN-786] Remove dotted border from related articles on focused article page

sass/includes/_content-block.scss, sass/includes/_related-resources.scss, sass/includes/_section-separator.scss
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-787
Adds styling to reduce width of specific content components on the focused article page type. This is to bring the content widths closer in line with the designs.
**Please note** - we could do with some more refinement for all common components shared between the article (story) and focused article pages. At the moment the padding is a little inconsistent between components - for example, some use `<div class="container">` while others don't, so the padding varies slightly between components.  This refinement is out of scope for this ticket but will need addressing to neaten things up longer term.
Review a focused article page and see that non-image components have …
=> [UN-787] Update component widths for focused articles

templates/articles/article_index_page.html, templates/articles/record_article_page.html, templates/collections/explorer_index_page.html, templates/collections/highlight_gallery_page.html, templates/collections/time_period_explorer_page.html, templates/collections/topic_explorer_page.html
Ticket URL: [UN-759]
I've chosen to just prevent pages from showing if they're not public (and by that, live) in the front-end. This is because editors can select a page as a featured article, and then make the page private/un-publish it. This then either takes the user to a password page, or to an error that the page doesn't exist. This eliminates that by checking if the selected page is public - if the page isn't public or live then it won't show.
Add a page to a featured article field, then unpublish the selected page or make it private - then view the original page where you added the featured article and see that it is missing.
Follow …
=> UN-759: Unpublished pages still showing in Featured Article

sass/includes/_hero-image.scss, sass/includes/_highlight-cards.scss, sass/includes/_highlight-intro.scss, templates/collections/topic_explorer_page.html, templates/includes/related-articles-highlight-cards.html, templates/includes/related-highlight-cards.html
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-776
Updated the topic & time period page container to ensure content resizes correctly on browser zoom.
Also adds a max-height to full-width hero images to ensure they also resize as expected in browser zoom.
Review topic/time period index page locally and use browser zoom (both in and out) to check the content resizes correctly.
This also applies to hero images on article pages.
Before: 
After:
=> [UN-776] Topic and Time Period Explorer Pages zoom

etna/collections/models.py
Ticket URL: [UN-785]
Re-written the `related_articles` attribute for the Topic and Time Period pages to include `ArticlePage` and `FocusedArticlePage`.
Added docstrings for a bit of explanation :) 
Go to http://localhost:8000/explore-the-collection/explore-by-topic/migration-and-citizenship/ or http://localhost:8000/explore-the-collection/explore-by-time-period/early-20th-century/ and ensure that Focused Articles are also in the articles section
[UN-785]: https://national-archives.atlassian.net/browse/UN-785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
=> UN-785: Topic and Time Period pages to have related Focused Articles

sass/tna-toolkit/_typography.scss
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-731
Updates the font family for headings to match up with the design system.
Check an article page with headings & subheading fields (or add your own) and see the fonts match those in the design system. 
Design: https://www.figma.com/file/uo8YY98lLws8E1HEfpdn5X/TNA-Etna---Design-system?type=design&node-id=7-272&mode=design&t=5RsJEfSMh7NLevVv-0
=> [UN-731] Fix font families for headings across the site

scripts/src/modules/analytics/search/search_filters_tracking.js
Ticket URL: [DF-723]
Created a list of filters to return "Yes" instead of the filter value. This makes it easier to add/remove the filter values we want to default to "yes" with :)
Do a search [(here's one I made earlier!)](http://localhost:8000/search/catalogue/?filter_keyword=&covering_date_from_0=1&covering_date_from_1=2&covering_date_from_2=1000&covering_date_to_0=2&covering_date_to_1=2&covering_date_to_2=2000&collection=WO&opening_start_date_0=&opening_start_date_1=&opening_start_date_2=&opening_end_date_0=&opening_end_date_1=&opening_end_date_2=&q=&sort_by=&sort_order=asc&group=tna) and check the `dataLayer` command in the console. There should be a "Yes" in place of the `search_filter_value` on the `covering_date` and `opening_date` filters.
Follow …
=> DF-723: FIX Tracking when a user selects a record Covering date filter

sass/includes/_hero-image.scss, templates/includes/hero-img.html
Ticket URL: n/a (I don't think anyway?)
Updates hero styles on desktop to fix the horizontal scroll issue on Chrome (windows)
Review focused article page with and without hero image & caption - see that there is no longer any horizontal scroll
=> Fix horizontal scroll on focused article page

templates/blocks/image-block-default.html, templates/includes/hero-img.html, templates/includes/highlight-intro.html
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-795
Fixes if statement for streamfield images so the alt text shows if they are _not_ marked as decorative
Add TODO comment for BE to add alt text field for hero images (both for article pages and topic/time period pages)
Review any story page and see that the alt text is being pulled through correctly to the FE for any images with alt text
=> [UN-795] Fix alt text for streamfield images and add TODO for heros

sass/includes/_card-groups.scss, templates/articles/blocks/related_item.html, templates/collections/blocks/promoted_pages.html, templates/home/blocks/featured_external_page.html, templates/home/blocks/featured_page.html, templates/includes/article-spotlight.html, templates/includes/related-articles-highlight-cards.html, templates/includes/related-highlight-cards.html
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-744
This removes `aria-hidden` and `tabindex="-1"` and replaces them with an `aria-labelledby` attribute for card image links, to make sure they are accessible to keyboard users. 
Check instances of cards and ensure the image links can be accessed via keyboard using the tab key and that the aria-label is working correctly. In most cases the aria-label is pointing to the title of the card, unless an alternative is provided. As long as the link text is not ambigious and is the same as the title link, this should not be an accessibility issue. 
Follow …
=> [UN-744] Re-instate card image links to the taborder

package-lock.json, package.json, sass/etna.scss, sass/includes/_buttons.scss, sass/includes/_footer.scss, sass/includes/_record-matters.scss, templates/includes/footer.html, templates/includes/highlight-intro.html
https://national-archives.atlassian.net/browse/UN-742
Reinstates updates from https://github.com/nationalarchives/ds-wagtail/pull/1127 (undone in https://github.com/nationalarchives/ds-wagtail/pull/1138) but fixes issues:
- `tna-footer` namespace updated to `etna-footer` so as not to cause conflicts
- Images requiring `display: inline-block;` fixed
- Focus styles fixed
This should then allow us to move forward with making a first stable version (`v1.0.0`) of `@nationalarchives/frontend`
Also added `load-path` parameter into the SASS compilation to allow import not to have to use relative `../node_modules` path.
=> Reinstate frontend styles, fix issues, update footer classes

templates/search/blocks/search_filters.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-714
Fix for date labels on search results
Perform a search and check layout and labelling of filter column 
=> DF-714-fix for date labels on search

etna/records/templatetags/records_tags.py, etna/records/tests/test_models.py, etna/records/tests/test_templatetags.py, templates/includes/records/hierarchy-global.html, templates/search/blocks/search_results__list-card--grid.html, templates/search/blocks/search_results__list-card.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-740
Show Archive links with iaid's in Record Details page and Search results
1) Select records from the results from Catalogue buckets
or
View Archive links on the record details pages in these sections of Hierarchy
- You are here - Archive link
- Detailed catalogue location (visible from show detailed view) - This record is held At link
Ex: using refs and ids
http://127.0.0.1:8000/catalogue/ref/ADM/
http://127.0.0.1:8000/catalogue/ref/J/77/3417/4284/
http://127.0.0.1:8000/catalogue/id/e48bb766-1199-4e23-8bd8-b179338cd831/
http://127.0.0.1:8000/catalogue/id/C4122893/
2) View archive records with iaid's in the results area from Find an Archive bucket
http://127.0.0.1:8000/search/catalogue/?group=archive …
=> DF-740: Fix archive links details page and search results

etna/articles/models.py, etna/articles/tests/test_similar_items.py, sass/tna-toolkit/_typography.scss, templates/articles/article_page.html
Ticket URL: [UN-780]
Added the three page types to the "More Stories" and "You may also be interested in" sections.
Open an article page, scroll to the bottom and see that the new page types are being included.
[UN-780]: https://national-archives.atlassian.net/browse/UN-780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UN-780: Record, Focused, and Article page types in "More Stories"

etna/search/templatetags/search_tags.py, etna/search/tests/test_search_tags.py, etna/search/tests/test_views.py, templates/search/blocks/search_filters.html, templates/search/blocks/search_sort_and_view_options.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-585
Sort by field is used for desktop and mobile. This PR make rendering of the fields with unique ids. 
- Navigate to Catalogue search bucket ex. tna
- Select sort by options
- View page source - for id_sort_by_desktop, id_sort_by_mobile uniqueness
=> DF-585:Fix uniqueness for sort_by id

etna/records/templatetags/records_tags.py, etna/records/tests/test_templatetags.py, templates/includes/records/hierarchy-full-item.html, templates/includes/records/hierarchy-global.html, templates/includes/records/hierarchy-short-item.html, templates/search/blocks/search_results__list-card--grid.html, templates/search/blocks/search_results__list-card.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-774
Changes to use id in Hierarchy and Search results for Department, Division, Sub-series, Sub-sub-series for tna records
Changes to use id in Hierarchy and Search results for Fonds, File, Item, Sub-item for nonTna
Navigate to results of search buckets
Filter level
Select the record for the above levels, it should not take you to the disambiguation page
Navigate through Hierarch links in record details
http://127.0.0.1:8000/catalogue/ref/WO/409/27/29/562/
http://127.0.0.1:8000/catalogue/ref/DF/106/7/
http://127.0.0.1:8000/catalogue/id/C162/
http://127.0.0.1:8000/catalogue/ref/ADM/159/
http://127.0.0.1:8000/catalogue/ref/DF/5/108/
http://127.0.0.1:8000/catalogue/id/66787951-2237-4f8a-882f-0ac275fe2bff/
Follow …
=> DF-774:Fix hierarchy and search results links for various record levels

templates/includes/record-revealed.html
Lizzy spotted a broken page label:
And I also realised it was linking incorrectly.
This fixes the link issue, and the label issue.
Edit an Article Page and add a "Featured Record Revealed" to the page. The element should then display correctly.
=> CHORE: Fix record revealed promo

package-lock.json
Updated
@babel/core 7.22.8 -> 7.22.9
@babel/preset-env 7.22.7 -> 7.22.9
=> CHORE: JavaScript package updates

package-lock.json, package.json, sass/etna.scss, scripts/src/article.js, scripts/src/modules/articles/accordion_functionality/accordion_functionality.js, templates/blocks/image-block-default.html
https://national-archives.atlassian.net/browse/UN-612
There was a bug where multiple images with transcripts in the same section wouldn't work.
This allows each transcript in a section to operate in isolation.
I also took the chance to update `@nationalarchives/frontend` to fix some bugs with the focus styles and remove some project-specific overrides.
Using staging data, there are two images with transcripts on `explore-the-collection/stories/richard-iii/`. They should now both be able to open and close independently of one another.
=> UN-612 - Multiple images with transcripts bug

sass/includes/_generic-intro.scss, sass/includes/_transcription.scss
Ticket URL: https://national-archives.atlassian.net/browse/DF-785
Small layout change to close button on record revealed
Go to a record revealed page, open the 'View image and transcript' button, check the layout of the 'Close Images and Transcripts' button
=> Layout fix on close button for record revealed

sass/includes/_transcription.scss
=> Add padding for transcript paragraphs and lists

.github/workflows/ci.yml, .github/workflows/main.yml
Removed step in CI where it ran if it was a push to `main` or `release/*`
=> CHORE: Fix CI running twice on main

.docker/update-npm/Dockerfile, .docker/update-poetry/Dockerfile, docker-compose.yml, docs/developer-guide/dependency-management.md, fabfile.py
This allows us to run `fab update-deps` to update all dependencies for npm and Poetry.
Two Docker instances are created and the updates happens inside them. This ensures a consistent environment for updating (identical versions of Python, Node etc.)
Behind the scenes, `fab update-deps` runs `docker-compose --profile update up -d` which starts up the two Docker instances defined in `docker-compose.yml`. Their volumes are mapped to the current working directory so they can write changes back and then they shut down after updating.
These two images are not affected by `fab build` or `fab start`.
In the future we can look to remove duplicated version definitions, possibly use nvm and maybe pyenv.
=> Create two Docker instances to update dependencies

etna/articles/models.py, etna/articles/tests/test_similar_items.py, templates/articles/focused_article_page.html
Ticket URL: [UN-781]
- Added `similar_items` property to `FocusedArticlePage` to retrieve pages (`FocusedArticle`, `RecordArticle`, `Article`) with similar tags to the current page.
- Added `latest_items` property to `FocusedArticlePage` to retrieve the latest published pages (`FocusedArticle`, `RecordArticle`, `Article`).
- Added these to the HTML to display the pages.
- Created tests for the property.
Open a Focused Article page, scroll to the bottom and see that there is a section for similar items, and latest items.
The FA page must be tagged in the "article tags" section on the promote admin panel - similar items will only work if there are other pages tagged with the same tag.
Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/ …
=> UN-781: Focused Article "You may be interested in" and "More stories"

templates/base.html, templates/search/featured_search.html
… no search term.
Ticket URL: https://national-archives.atlassian.net/browse/DF-715
Adding in a 'Skip o search results' anchor, for both search term and no search term
Perform a search, check source code for sr-only : Skip to search results, click link to check that the anchor link works. Try with a search term and without. Check mobile view also.
=> DF-715-Applying anchor for 'Skip to search results'

templates/search/long_filter_options.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-316
Moved the 'Cancel and return to results' link outside the <form> element
Perform a search, chose 'more filters', check that the 'Cancel and return to results' link  displays correctly and functions corectly across viewports. Check with screen reader software - I used https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn
=> DF-316-moving the cancel link outside of the <form> element

sass/etna.scss, templates/includes/breadcrumb.html
=> Fix top of page on featured articles

templates/includes/header.html
The search menu item won't work unless it is made visible across the whole site which we don't want on the beta site but was fine on the development site.
=> Fix search menu item

package-lock.json, package.json, poetry.lock, pyproject.toml
**poetry:**
django-allauth 0.54.0 -> 0.55.0
mkdocs-material 9.1.21 -> 9.2.5
**npm:**
jest-environment-jsdom 29.6.2 -> 29.6.4
babel/core 7.22.10 -> 7.22.11
jest 29.6.2 -> 29.6.4
sass 1.65.1 -> 1.66.1
=> CHORE: Update dependencies

etna/feedback/templates/feedback/widgets/response_submit_button_list.html, sass/includes/_feedback.scss
Ticket URL: https://national-archives.atlassian.net/browse/DF-806
Layout changes to allow three feedback mechanism buttons to display inline
Test Desktop and mobile view to check that three buttons display inline (see screenshot also)
=> DF-806-feedback-mechanism-buttons

templates/base.html, templates/search/featured_search.html
- Add back in condition from https://github.com/nationalarchives/ds-wagtail/commit/da35fea37b63af9d60043297e3faa3824f4409af#diff-690b81fad8df2a1f1ce37c846641d9247e3472d244f17039d2910a5ed0c98d5eL86-L88
- Remove extra space in `id` attribute
=> Remove results skip link from non-search pages

sass/includes/search/_long-filters.scss, templates/search/long_filter_options.html
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/issues/DF-316
Moving the Apply Filters button within the form element on long filters page.
Check that the Apply Filters button is within the form and works as expected
=> DF-316-moving-the-Apply-filters-button-within-the-Form-element

scripts/src/modules/analytics/search/search_sort_filters_tracking.js
Ticket URL: [DF-759]
Added logic to check if the user is on `id_sort_by_desktop` or `id_sort_by_mobile`, and then set the `selectElement` variable based on that condition.
I'm not entirely sure how to check as the dataLayer push happens on submitting the form - when you submit the form the page reloads and you lose it from the `dataLayer` command in the console.
[DF-759]: https://national-archives.atlassian.net/browse/DF-759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DF-759: FIX Rebuild Event sort search results

etna/search/forms.py
Ticket URL: https://national-archives.atlassian.net/browse/DF-820
Changes the Date in Sort By filter to sort by `Covering Date` (which is API `dateCreated`) instead of `Record Opening date` (which is `dateOpening`)
- Navigate to Catalogue Search - TNA
- Select Sort By `Date` and Update.  (Also try filter on a smaller date range with this)
- The results should be sorted by Date in the Results area. (At the moment, there seems to be some data issues with KONG with the values returned. This has been identified and taken up separately)
=> DF-820:sort-by-covering-date

sass/includes/_filters.scss, templates/whatson/whats_on_page.html
As per slack discussion with @jamesbiggs, we don't want to insist that a date has a default value. This branch fixes the iOS styling with a min-width instead.
View the whats on listing page and check the date style in IOS
=> Fix date styling for iOS so we don't need a default value

templates/whatson/whats_on_page.html
Added price_range to featured event and event cards - will currently only display "Free" as the price cannot be edited in Wagtail at the minute.
=> What's On Page: Added price_range to featured event and event cards

scripts/src/article.js, scripts/src/modules/analytics/hero-captions.js
https://national-archives.atlassian.net/browse/UN-616
Data should be added to the window's `dataLayer` object on opening and closing hero element captions:
- http://localhost:8000/explore-the-collection/stories/Policing-migration/
- http://localhost:8000/explore-the-collection/stories/richard-iii/
=> Add tracking to hero banner details toggle

etna/whatson/models.py, etna/whatson/tests/test_pages.py, templates/includes/whats-on-listing.html, templates/whatson/whats_on_page.html
No ticket
The featured event card is meant to have the filtering applied, just like the other event cards, and should not be repeated in the list below.
This adds some extra queries to work with the featured card, if it has been added. It also moves more of the markup from the whats on template to the whats on listing include, so that the featured card can be updated with JavaScript.
Add a few events to a whats on listing page, and also add a featured event. Check that the filtering behaves as you expect, and that the featured event is not repeated in the listing below.
Also check the page when there is no featured event selected.
You could also test that it works without JS by setting the `FEATURE_DISABLE_JS_WHATS_ON_LISTING` to True in your `.env` file (note that you need to run `fab …
=> Filtering of featured event card

etna/authors/models.py
Ticket URL: [UN-808]
Added `gtm_content_group` and `get_datalayer_data` overrides, with the required data as per the ticket
Load up an Author page, enter dev tools and type `dataLayer` into the console. You should see `contentGroup1` and `customDimension3` both set to "Author page"
[UN-808]: https://national-archives.atlassian.net/browse/UN-808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UN-808: Author Page BE analytics

templates/authors/author_page.html, templates/includes/footer.html
- [Fix spelling error](https://github.com/nationalarchives/ds-wagtail/commit/9d85da95f415c1c047a48ef86571aeefad35d29a)
- [Add missing spacing on author page](https://github.com/nationalarchives/ds-wagtail/commit/821f32c96fc4e2f67e7a2b445e3686d93d524deb)
=> Spelling mistake and spacing

sass/includes/_filters.scss, scripts/src/modules/filters-submission.js, templates/whatson/whats_on_page.html
[Ticket URL:](https://national-archives.atlassian.net/browse/DSWO-47)
Addresses the following feedback points from ticket 47:
- The buttons on the filters need type="button" added else they act as submit buttons when JavaScript is disabled.
- I’m not sure how helpful the text “Format: dd/mm/yyyy” for the date selector is as the format will be driven be the preferences of the operating system and browser ([<input type="date"> - HTML: HyperText Markup Language | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#value)) - it might be easier to omit this hint.
- I think we could do with adding a cursor: pointer; to the toggle buttons to indicate interactivity.
Not addressed:
- Changing the style of the applied filters, as discussed with Lauren in stand-up
- The issue …
=> [DSWO-47] - feedback on filters

sass/etna.scss, templates/includes/header.html, templates/whatson/event_page.html, templates/whatson/whats_on_page.html
[ part of this ticket](https://national-archives.atlassian.net/jira/software/projects/DSWO/boards/121?selectedIssue=DSWO-46)
This adds the correct header colour for the what's on pages. Note that the solution was not simply to completely remove the `tna-header--accent ` class from the header, as that left the background colour as black, whereas the designs use the off-black `#1e1e1e` which isn't currently available in `tna-frontend`. Therefore I've added another override in `etna.scss` to set the correct background class for the whats on header - this can be moved to `tna-frontend` in the future.
In your local build, test the whats on listing page, and an individual event page.
Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contr …
=> Off-black header colour for whats on pages

etna/ciim/constants.py, templates/search/blocks/search_sort_and_view_options.html
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/issues/DF-834
Change to the 'Website results' tab and adding in some helper text on 'Website results' page.
Check that the tab now reads 'Our website results'
Check that the helper text 'Results for everything on our website that matches your search term.'
=> DF-834 Improvements to website results tab

templates/includes/records/record-details.html, templates/records/record_detail.html, templates/search/blocks/search_results__list-card--grid.html, templates/search/blocks/search_results__list-card.html, templates/search/includes/results-details.html
Ticket URL: N/A
- There are effectively no changes in terms of UI.
- Update search, record details templates to accommodate specific bucket details. The specific bucket would be for OHOS - which is forked out from Etna or any other buckets in the future. (Eg. for OHOS it is results-details-community.html, record-details-community.html - in terms of choice of attributes and ordering of fields.)
- If required, in the future for Etna, a specific bucket will use a specific results/details template.
Search results
http://127.0.0.1:8000/search/catalogue/?group=tna
http://127.0.0.1:8000/search/catalogue/?group=tna&display=list
http://127.0.0.1:8000/search/catalogue/?group=tna&display=grid
Record Details
http://127.0.0.1:8000/catalogue/id/C8077549/
Follow …
=> CHORE:update search, record details templates to accommodate specific bucket details

etna/ciim/tests/test_utils.py, etna/collections/tests/test_models.py, etna/core/tests/test_decorators.py, etna/core/tests/test_middleware.py, etna/records/tests/test_blocks.py, etna/records/tests/test_models.py, etna/records/tests/test_urls.py, etna/records/tests/test_views.py
Ticket URL: NA
- issue running tests says
```
ERROR: test_no_links (etna.ciim.tests.test_utils.TestResolveLinks.test_no_links)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/app/etna/ciim/tests/test_utils.py", line 127, in test_no_links
self.assertEquals("<span/>", stripped_markup)
^^^^^^^^^^^^^^^^^
AttributeError: 'TestResolveLinks' object has no attribute 'assertEquals'. Did you mean: 'assertEqual'?
FAILED (errors=38, skipped=37)
```
- update assertEquals to assertEqual that is [compatible with python 3.12](https://docs.python.org/3/whatsnew/3.12.html#id3) 
Run test locally should not throw failures
```
----------------------------------------------------------------------
Ran 476 tests in 18.196s
OK (skipped=37)
``` …
=> FIX:Fix test compatible with python 3.12

sass/etna.scss
Ticket URL: https://national-archives.atlassian.net/browse/DOR-35
This PR addresses the general styling issues of the navigation. This was raised as part of the record detail page review but it's a global issue not specific to that page template, so I'm addressing it here to review separately.
In the ticket we discussed removing or hiding the nav bar, but I've adjusted the styling instead to avoid completely removing the nav on the detail page. Saves any potential problems down the line or inconsistencies between templates which show/don't show the nav.
Note that this is a temporary fix for now while we don't have the new header built, to reduce accessibility issues with the current styles which are a bit broken.
Check any page on the site and click through the tabs to make sure all …
=> DOR-35: Fix navigation styles

etna/feedback/templates/feedback/admin/feedbacksubmission_index.html
Ticket URL: [EDEV-87]
Updated `feedbacksubmission_index.html` to use https://github.com/wagtail/wagtail/blob/stable/6.0.x/wagtail/admin/templates/wagtailadmin/shared/export_buttons.html
http://localhost:8000/admin/snippets/feedback/feedbacksubmission/ and see that the dropdown is fixed
[EDEV-87]: https://national-archives.atlassian.net/browse/EDEV-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDEV-87: Fix "Download XLSX" and "CSV" dropdown

etna/articles/models.py, etna/authors/models.py, etna/authors/tests/test_models.py, etna/collections/models.py, etna/core/serializers.py, templates/articles/focused_article_page.html
Ticket URL: [EDEV-32]
This PR is a bit of a combined one - but they're both in the same vein so made sense to do them together. They both follow the same structure so thought it best to do it all in one.
This covers:
[EDEV-37] and [EDEV-55]
EDEV-37 covers the `topics` and `time_periods` fields - which are used on multiple other page types, not just article pages.
EDEV-55 covers the `authors` fields - which are only used on `FocusedArticlePages` but as I mentioned, follow the same structure as the `topics` and `time_periods`. This serializes the data so that we get a bit more useful info rather than just a page ID.
I also had to slightly restructure how we manage `authors` because I didn't do it too well the first time round. These function the exact same as `topic` and `time_periods` now. …
=> EDEV-32: Article Pages API response

config/urls.py, etna/ciim/constants.py, etna/search/forms.py, etna/search/views.py
Ticket URL: https://national-archives.atlassian.net/browse/DOR-55
- Limit the search results to digitised records only, ignore the URL `group` param's value.
- Refactor of #1550. Using subclass instead of overriding code directly.
Use the search catalogue: http://localhost:8000/search/catalogue/
- Should only return the digitised results, whatever happens.
=> [DOR-55] Limit search results to digitised records only

etna/media/templates/wagtailmedia/chooser/chooser.html
Ticket URL: [EDEV-89]
Updated media chooser HTML to use `field.html` wrapped in `<li>` tags rather than `field_as_li.html` which was recently deprecated.
Find an article with a media chooser (or add one) and then select a media item from the chooser panel.
[EDEV-89]: https://national-archives.atlassian.net/browse/EDEV-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDEV-89: Fix media chooser

sass/etna.scss, sass/includes/search/_featured-search.scss, sass/includes/search/_no-results.scss, templates/search/blocks/no_results.html, templates/search/blocks/search_results_hero.html, templates/search/catalogue_search.html
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/DOR/boards/128?selectedIssue=DOR-56
This PR addresses the styling issues for the 'no search results found' page.
Load up the [search page locally ](http://localhost:8000/search/catalogue/) and search for something that doesn't exist : )
Before:
After:
=> DOR-56: 'No results' search results page (FE)

config/settings/dev.py, config/settings/util.py, etna/tests/test_config.py
`strtobool` function was returning an integer.
I realised this because we were passing `1` instead of `True` to the verify certificates option in HTTP requests in the CIIM client. It only broke when making requests to HTTPS, because requests were looking at a custom certificate at a filesystem path `1`, rather than just using the default verify certificate behaviour.
It might be because this is the first time we used HTTPS instead of HTTP using this API client.
`strtobool` is used heavily in the codebase, and if the rest of the code was not changing an integer to the boolean, there may be side effects once this is merged.
Alternatively, we could ensure whenever this function is used, we explicitly cast return values to the boolean at the call time. I don't know the original reason for …
=> Make strtobool() return a boolean value, not an integer (0, 1)

templates/includes/image_gallery.html
Images in record revealed articles are displayed in their original size. This is too large.
This change restricts the image to a maximum dimension of 1024px.
=> Restrict image sizes in record revealed articles

etna/ciim/utils.py
Ticket URL: https://national-archives.atlassian.net/browse/EDEV-95
strip_html is already called with mark_safe exclusively [here ](https://github.com/nationalarchives/ds-wagtail/blob/71a126411d748aaa3d0faed8664f7ad33307797b/etna/records/models.py#L159)and [here](https://github.com/nationalarchives/ds-wagtail/blob/71a126411d748aaa3d0faed8664f7ad33307797b/etna/records/models.py#L270). 
and is not originally called from [here ](https://github.com/nationalarchives/ds-wagtail/blob/71a126411d748aaa3d0faed8664f7ad33307797b/etna/records/models.py#L292)
This removes the duplicate call in strip_html method and restore original functionality for content attribute
- View search results - http://127.0.0.1:8000/search/catalogue/
- View record details from the search results
Follow …
=> EDEV-95:Remove call to mark_safe

templates/search/blocks/search_results.html
Ticket URL: https://national-archives.atlassian.net/browse/DOR-81
Hides any results which don't contain a thumbnail. This is a temporary fix for user testing, to hide parent records in our subset of record results which don't contain thumbnails. 
**Note:** this will need to be reverted after user testing (or at an agreed time) to ensure we don't unintentionally hide any records without thumbnails in future (see ticket https://national-archives.atlassian.net/browse/DOR-82)
=> [DOR-81]: Temporarily hide records without thumbnails from search results

sass/includes/_jumplinks.scss
Ticket URL: https://national-archives.atlassian.net/browse/DOR-79
This change adds a small left padding to the nav, which does mean its no longer completely flush with the left hand side. This will likely be re-factored later anyway, so this is a fairly short-term fix for now until the new front-end is brought in properly.
Before:
After:
=> [DOR-79] Fix sidebar / jumplinks focus state being cut off

etna/core/blocks/image.py
Ticket URL: [EDEV-93]
Added transcript + translation values from the CustomImage model to the returned JSON when the APIImageChooserBlock is turned into the API representation.
http://localhost:8000/api/v2/pages/202/ and look at some images
[EDEV-93]: https://national-archives.atlassian.net/browse/EDEV-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDEV-93: Image Block transcript + translations

etna/articles/models.py, etna/collections/models.py, etna/core/models/mixins.py
Ticket URL: [EDEV-88]
Added `ContentWarningMixin`'s `api_fields` to `ArticlePage`'s `api_fields`.
Added `display_content_warning` to the Mixin's `api_fields` so the front-end knows whether to display the default (or custom) warning.
[EDEV-88]: https://national-archives.atlassian.net/browse/EDEV-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDEV-88: Content warning

etna/articles/models.py
Ticket URL: [EDEV-38]
Removed verbose_public_name APIFields - we get this coming through, capitalised, in `type_label` which we are sending to the API response via BasePage.
[EDEV-38]: https://national-archives.atlassian.net/browse/EDEV-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDEV-38: verbose_public_name

etna/ciim/tests/test_utils.py, etna/ciim/utils.py
Ticket URL: https://national-archives.atlassian.net/browse/EDEV-98
- Update method comments
- Set method defaults
- Added allow_tags (used for OHOS, does not change existing functionality)
- Added tests
Regression:
- http://127.0.0.1:8000/search/catalogue/?q=D7376859&group=digitised
- http://127.0.0.1:8000/catalogue/id/D7376859/
=> Feature/EDEV-98: updates for strip html

config/settings/base.py, docker-compose.yml
Set up redis config for services not on platform.sh, ready for AWS
Setup is described here: https://docs.wagtail.org/en/stable/advanced_topics/performance.html
=> Add redis config for services not on platform.sh

etna/api/tests/expected_results/article.json, etna/api/tests/expected_results/article_index.json, etna/api/tests/expected_results/arts.json, etna/api/tests/expected_results/author.json, etna/api/tests/expected_results/authors.json, etna/api/tests/expected_results/early_modern.json, etna/api/tests/expected_results/focused_article.json, etna/api/tests/expected_results/highlight_gallery.json, etna/api/tests/expected_results/pages.json, etna/api/tests/expected_results/postwar.json, etna/articles/models.py, etna/collections/models.py, etna/core/blocks/image.py, etna/core/models/basepage.py, etna/core/serializers/images.py
- Update intro image size in `RecordArticlePage`
- Change all default `webp_quality` from `80` to `60`
- Add `HeadlessMixin` to `BasePage` and remove `HeadlessPreviewMixin`
- Removed unused `teaser_image_large`
=> Image size tweaks and add headless mixin

.devcontainer/docker-compose.yml, docker-compose.yml
When running `fab build` etc on my new laptop, Docker informed me that the use of `version` is no longer needed. Tested on my old laptop and it also ran fine, so it seems like `version` is redundant on both new and old versions of Docker.
This PR removes `version` from both `docker-compose.yml` files in the project.
=> CHORE: Remove `version` from docker-compose.yml

config/settings/base.py
Allow the frontend to query more child pages in a single request for things like the sitemap.
At the moment, a maximum of 20 pages can be returned at once.
E.g. http://localhost:8000/api/v2/pages/?limit=100
=> Add setting for WAGTAILAPI_LIMIT_MAX

.platform.app.yaml
Ticket URL: https://national-archives.atlassian.net/browse/EDEV-126
To Fix: Warning: less than 20% disk space in National Archives - Etna Wagtail / main / app
Logon to psh and review persistent disk metric
=> EDEV-126:increase disk space on psh

.platform.app.yaml
Ticket URL: https://national-archives.atlassian.net/browse/EDEV-126
To Fix: 
1.Warning: less than 20% disk space in National Archives - Etna Wagtail / main / app
2. E: Error: Resources exceeding plan limit; disk: 5632.00MB > 5120.00MB; try removing a service, or add more storage to your plan
`4608+512(db) = 5120`
=> EDEV-126:adjust/increase disk space psh

etna/api/urls.py
This adds an `author_view` endpoint, which allows us to get a list of authors (and their details) and how many blog posts they are marked as an author on.
Go to http://localhost:8000/api/v2/blog_posts/authors/ and see the data
=> Blog API: `author_view`

etna/alerts/tests.py, etna/articles/blocks.py, etna/blog/blocks.py, etna/ciim/tests/test_models.py, etna/collections/models.py, etna/collections/tests/test_views.py, etna/core/tests/test_decorators.py, etna/generic_pages/blocks.py, etna/people/tests/test_models.py, etna/records/blocks.py, etna/records/models.py, etna/records/templatetags/records_tags.py, etna/records/tests/test_blocks.py, etna/records/tests/test_models.py, etna/records/tests/test_views.py, etna/records/transforms.py, etna/records/views/choosers.py, etna/records/views/images.py, etna/records/views/records.py, etna/search/forms.py, etna/search/tests/test_views.py, etna/search/views.py
Following a discussion on the developer catch-up, we decided it would be good practice to only use relative imports within the immediate module, e.g.
in etna.articles.blocks.py, this is fine:
`from .models import ArticlePage`
but we shouldn't use them like this:
`from ..media.blocks import MediaBlock`
and should instead be writing:
`from etna.media.blocks import MediaBlock`
It adds unnecessary additional cognitive load. The two apps are not immediately related to one another - `etna.media` can exist without `etna.articles` (in theory). So there is a chance that the path may change. It also makes it easier to trace where you are importing things from, and makes it clear to a developer trying to understand your code.
=> Replace relative imports for imports outside of the immediate module

etna/api/tests/expected_results/article.json, etna/api/tests/expected_results/article_index.json, etna/api/tests/expected_results/arts.json, etna/api/tests/expected_results/author.json, etna/api/tests/expected_results/early_modern.json, etna/api/tests/expected_results/focused_article.json, etna/api/tests/expected_results/highlight_gallery.json, etna/api/tests/expected_results/pages.json, etna/api/tests/expected_results/people.json, etna/api/tests/expected_results/postwar.json, etna/api/urls.py, etna/core/models/basepage.py
1. Add `last_published_at` to http://localhost:8000/api/v2/pages/
2. Simplify adding `depth` to API fields still allows ordering by depth: http://localhost:8000/api/v2/pages/?ancestor_of=412&order=depth
=> Add last published to pages endpoint and simplify depth field

config/settings/base.py
This stops people being able to upload HTML files (among others) that contain malicious code
=> Restrict document extensions

etna/ciim/client.py, etna/records/fields.py
Temporary fix for errors being raised if a record does not exist in CIIM. This will need some work to gracefully handle errors in the future, in case a record is taken down from CIIM, or CIIM goes down in the future.
=> Return None if record does not exist or multiple objects returned

etna/records/templatetags/records_tags.py
We're having issues on pages such as https://beta.nationalarchives.gov.uk/explore-the-collection/stories/margaret-bondfield/ because the page is attempting to get the record `iaid` value - however due to missing data from CIIM, we're getting a `NoneType` error. This fix will temporarily return "" if there is no record data. This will be fixed in the new search app, and when the CIIM data returns.
=> If record does not exist, return ""

etna/blog/models.py
Adds an override for `type_label` on `BlogPostPage` to show which blog the post is under.
=> Set BlogPostPage chips to the parent blog title

etna/core/models/basepage.py, etna/core/serializers/__init__.py, etna/core/serializers/pages.py
Adds an `AliasOfSerializer` to serialise `alias_of` values on the detail view of all pages. This is because by default, we get
which isn't massively useful for the frontend. Now we get
which we can update to include different values. But as it stands, these are the most useful values to us.
=> AliasOfSerializer

etna/api/tests/expected_results/author.json, etna/people/models.py
Adds `BlogPostPage` to the `authored_focused_articles` (will keep this name for now as to not mess with the current frontend) so that `is_author` status is given if they are credited on a blog (not just focused articles)
=> Update `is_author` to include blogs

etna/api/urls.py, etna/core/models/basepage.py, etna/core/serializers/redirects.py
- All redirects: http://localhost:8000/api/v2/redirects/
- Single redirect: http://localhost:8000/api/v2/redirects/20/
- Find a redirect by its path: http://localhost:8000/api/v2/redirects/find/?path=/insight-pages/horatio-nelson -> http://localhost:8000/api/v2/redirects/20/
- Find a redirect by its path with incorrect slashes: http://localhost:8000/api/v2/redirects/find/?path=insight-pages/horatio-nelson/ -> http://localhost:8000/api/v2/redirects/20/
> In local dev, the redirects may go to http://host.docker.internal:8000 - this won't matter to the container
=> Add Redirects API endpoint and serializer

etna/api/tests/expected_results/article.json, etna/api/tests/expected_results/article_index.json, etna/api/tests/expected_results/arts.json, etna/api/tests/expected_results/author.json, etna/api/tests/expected_results/early_modern.json, etna/api/tests/expected_results/focused_article.json, etna/api/tests/expected_results/highlight_gallery.json, etna/api/tests/expected_results/people.json, etna/api/tests/expected_results/postwar.json, etna/api/urls.py
This means the frontend won't have to make a follow-up call of something like http://localhost:8000/api/v2/pages/?ancestor_of=192&order=-depth after the initial page request.
=> Add breadcrumbs metadata to CustomPagesAPIViewSet response

etna/api/urls/images.py, etna/api/urls/media.py, etna/core/serializers/images.py
Changed how Media items are being serialized on the `/media` endpoint so that the `chapter` field comes back ordered (and we can now change what comes back, etc)
Changed how CustomImage items are being serialized so that we can return renditions (like we do across the site) in the default representation of `/images` and taken the rendition generation outside of the serializer so we can use it in other places (as seen in this PR)
=> `/media` and `/images` endpoint updates

etna/api/filters.py, etna/api/urls/pages.py
Allows searching part of the site:
- http://localhost:8000/api/v2/pages/?search=victoria
- http://localhost:8000/api/v2/pages/?search=victoria&descendant_of_path=/
- http://localhost:8000/api/v2/pages/?search=victoria&descendant_of_path=/explore-the-collection/
- http://localhost:8000/api/v2/pages/?search=victoria&descendant_of_path=/explore-the-collection/stories/
Used to enable a search page on Explore the collection (https://develop.tna.dblclk.dev/explore-the-collection/search/)
=> Add DescendantOfPathFilter to enable filtering by page URI

etna/ciim/client.py
Rosetta was updated causing https://rosetta-prod.k-int.com/rosetta/data/search?q=* to return a different data schema, missing out some properties (e.g. IAID).
This adds a `filter` parameter in to the API requests (https://rosetta-prod.k-int.com/rosetta/data/search?q=*&filter=@datatype.base:record) in order to produce the expected result.
=> Refactor CIIMClient constructor to use superclass initialisation and add default filter parameter

app/api/urls/images.py, app/core/serializers/images.py
This PR updates the `image_generator` function so that we can create all of our renditions for an image in one call.
This also removes `additional_formats` in favour of just `formats` which allows us to dynamically generate different formats - or exclude jpeg/webp, which were (and still are) the default formats.
=> Use `get_renditions` instead of individual `get_rendition` calls
