- etna/quotes/blocks.py
- templates/quotes/blocks/quote.html
[DS-236]
[DS-236]: https://national-archives.atlassian.net/browse/DS-236
> Rename title as heading in quote block

- templates/quotes/blocks/quote.html
[DS-236]
[DS-236]: https://national-archives.atlassian.net/browse/DS-236
> Fix attribution logic in template

- templates/includes/hero-img.html
[DS-259]
[DS-259]: https://national-archives.atlassian.net/browse/DS-259
> Use hero_image field in template

- templates/paragraphs/blocks/paragraph-with-heading.html
[DS-237]
[DS-237]: https://national-archives.atlassian.net/browse/DS-237
> Update paragraph template to match static formatting

- sass/includes/_generic_intro.scss
Thanks for spotting the `em` issue.
Thanks :+1:
> Change generic-intro em uses to rem

- etna/ciim/tests/factories.py
- etna/collections/tests/test_models.py
Record description override is already merged in. This PR just adds some tests.
> Add tests for record description override

- etna/ciim/client.py
- etna/ciim/exceptions.py
- etna/ciim/models.py
- etna/ciim/tests/factories.py
- etna/ciim/tests/test_client.py
- etna/ciim/tests/test_models.py
- etna/collections/tests/test_views.py
- etna/records/views.py
- templates/includes/disambiguation-explanation.html
- templates/records/record_disambiguation_page.html
While working on the disambiguation page. I took the opportunity to refine the `SearchManager` and improve the tests.
> Integrate with disambiguation page with latest frontend changes DS-278

- etna/ciim/tests/fixtures/record.json
- etna/ciim/tests/test_models.py
- etna/ciim/utils.py
- etna/records/models.py
- templates/includes/records/key-facts.html
- templates/includes/records/record-details.html
This is a small change to extract held_by from a Kong response.
> Parse RecordPage.held_by from Kong response

- sass/includes/_hero-image.scss
- templates/includes/hero-img.html
Hi @gtvj,
This PR amends how the hero image is rendered so that it maintains prominence as screen size decreases. Would it be possible to merge if you are happy? Thank you 👍
> Amend hero image implementation

- templates/includes/records/hierarchy-global.html
Hi @matt-blair - could you look at this PR. It's just adding an ID to the summary element for tracking purposes.
> Add ID to summary element for tracking purposes

- sass/includes/_media-embed.scss
Hi @gtvj,
Would it be possible to merge this PR if you are happy? It's just a small one; it just fixes a bottom spacing issue for icons/labels on media embeds. Thank you 👍
> Fix media embed icon spacing

- templates/account/login.html
This will cover where there are non-field errors, including:
- User not found
- Too many failed attempts
> Add validation messages for additional circumstances

- scripts/src/details.js
- scripts/src/explorer.js
- scripts/src/home-page.js
- scripts/src/image-browse.js
- scripts/src/image-viewer.js
- scripts/src/insights.js
- scripts/src/modules/analytics/add_data_link.js
- scripts/src/modules/analytics/audio_tracking.js
- scripts/src/modules/analytics/card_position.js
- scripts/src/modules/analytics/push_to_data_layer.js
- scripts/src/modules/analytics/scroll_tracking/calc_scroll_percent_increment.js
- scripts/src/modules/analytics/scroll_tracking/get_scroll_percentage.js
- scripts/src/modules/analytics/scroll_tracking/update_scroll_obj.js
- scripts/src/modules/analytics/video_tracking.js
- scripts/src/modules/manage_details_element.js
Hi @JamesWChan - could you have a look at this PR? 
It introduces all the GTM tracking code that had previously been stored in a separate repo. The reason for this change is that we've been informed by the analytics team that their previous approach of adding scripts via the GTM console is no longer preferred and they would like us instead to include the scripts within the main repo.
> Add GTM JavaScript to Wagtail repo and refactor

- sass/includes/_quote.scss
This change has been requested by editorial in the UAT spreadsheet.
> Remove italicisation from citation in quote component

- etna/records/views/records.py
- templates/records/image-viewer.html
- templates/records/record_disambiguation_page.html
Some reference numbers return 10,000+ records!
Adding pagination to `SearchQuery` to handle large result set.
> Paginate disambiguation page

- config/settings/base.py
- etna/media/forms.py
- etna/media/templates/wagtailmedia/chooser/chooser.html
- poetry.lock
- pyproject.toml
Removed unused, and confusing, fields (width, height, thumbnail)
Got date picker working
Added validation so uploaded files will match the media type.
Removed upload tabs from chooser until Torchbox (completely) fix an [issue](https://github.com/torchbox/wagtailmedia/releases/tag/v0.7.1) with RichText fields.
> Improve media embed editor experience

- templates/404.html
Hi @JamesWChan - this PR is just to improve the presentation of the 404 page.
> Add structure to 404 page for display purposes

- templates/collections/results_page.html
[DS-320]
[DS-320]: https://national-archives.atlassian.net/browse/DS-320
> Explorer - results page: Hide the 'sort' block

- templates/includes/header.html
This change has been requested by editorial this afternoon.
> Update header text

- poetry.lock
[DS-323]
[DS-323]: https://national-archives.atlassian.net/browse/DS-323
> Update Wagtail v2.14.1

- scripts/src/modules/analytics/audio_tracking.js
- scripts/src/modules/analytics/video_tracking.js
This has been requested by the analytics team today
> Add event property to datalayer push for audio and video

- templates/insights/insights_index_page.html
Would you be able to merge this branch?
As discussed the H2 has a container and `sr-only` class now.
Thanks :+1:
> Add container & sr-only to insights index page h2

- sass/etna.scss
- sass/includes/_record-related-content.scss
- sass/includes/_record-related-records.scss
- templates/includes/records/record-related-content.html
- templates/includes/records/record-related-records.html
- templates/records/record_page.html
Hi @danbentley,
Here are the commits for styling the related records.
Matt.
> Adding SASS/HTML and attributes to related records content

- .editorconfig
- package-lock.json
- package.json
Hi @AshTNA,
Would it be possible to have a quick look at this PR? It introduces Jest for unit testing and a `.editorconfig` file where we can put our formatting rules once we've decided on them. Thank you 👍 
@gtvj - Just mentioning you in case you'd like to have a look
> Introduce jest for unit testing and editorconfig for code formatting

- etna/insights/blocks.py
This PR addresses the issues identified with CI, including: 
* Formatting issues identified by flake8
* Module import sorting with isort
> Fix CI issues

- templates/includes/footer.html
Added sr-only span with required text to make links more accessible for screen reader users, which fixes #169.
> Added sr-only span to fix issue#169

- fabfile.py
Replaces the `delete_dump_after` argument with separate `delete_dump_on_success` and `delete_dump_on_error` arguments for clearer control over the outcome, and 'less weird' error handling code.
> CHORE: Improve readability of restore_db() if fabfile

- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .gitignore
- .vscode/launch.json
- Dockerfile
- README.md
- docker-compose.yml
- fabfile.py
- Rewrites Dockerfile to install poetry without using a virtualenv
- Adds some files to for VS Code to pick up
> Disable poetry virtualenv and add devcontainer setup for VS Code

- etna/records/field_labels.py
- etna/records/templatetags/records_tags.py
- templates/includes/records/hierarchy-global.html
- templates/includes/records/hierarchy-local.html
- templates/includes/records/key-facts.html
- templates/includes/records/record-details.html
- templates/includes/records/record-title.html
- templates/insights/blocks/featured_record.html
- templates/records/record_detail.html
- Changes to replace fixed field labels with configured dict human readable values in record-details template
> DF-85:Implement Wagtail config for template handling

- etna/search/tests/test_forms.py
- etna/search/views.py
- sass/etna.scss
- sass/includes/search/_search-landing-buckets.scss
- sass/includes/search/_search-landing-hero.scss
- templates/search/blocks/search_landing_buckets--bordered.html
- templates/search/blocks/search_landing_buckets.html
- templates/search/blocks/search_landing_hero.html
- templates/search/search.html
Hi @danbentley 
Here's the rest of the search landing HTML. I've put the buckets into an include so there's another task of making the  bucket content dynamic to add to the list!
Thanks :+1:
> Incorporate search landing HTML/SASS

- etna/records/widgets.py
Fix to show record in admin results page when in Editing mode
> Fix to show record in admin results page when in Editing mode

- templates/search/blocks/search_export_and_share.html
- templates/search/blocks/search_filters.html
- templates/search/blocks/search_results__list-card.html
- templates/search/catalogue_search.html
Needed for upcoming user testing
> Conditionally show/hide UI components

- etna/ciim/client.py
- etna/ciim/tests/test_client.py
Fix incorrect param names - closingStartDate, closingEndDate with createdStartDate, createdEndDate. 
Thanks @AshTNA :)
> Fix/df 208-Fix incorrect param names

- config/urls.py
- etna/search/tests/test_views.py
- etna/search/views.py
- templates/search/blocks/search_filters.html
- templates/search/catalogue_search_long_filter_chooser.html
- templates/search/includes/filter.html
Resolves: https://national-archives.atlassian.net/browse/DF-211
Am also taking this opportunity to remove some of the duplication from the `templates/search/blocks/search_filters.html` template
> DF-211: Conditionally output link to long filter page

- etna/search/templatetags/search_tags.py
- etna/search/views.py
- poetry.lock
- pyproject.toml
- sass/includes/_global.scss
- templates/search/blocks/featured-search__interpretive-card.html
- templates/search/blocks/featured-search__record-creator.html
- templates/search/blocks/featured-search__results-block.html
- templates/search/blocks/search_results__list-card--grid.html
- templates/search/blocks/search_results__list-card.html
Hi @ababic 
Would you be able to merge this PR if all is OK?
Thanks :+1:
> DF-80: Implement search term highlighting for results 

- etna/search/views.py
- templates/base.html
Resolves ticket: https://national-archives.atlassian.net/browse/DF-230
> DF-230: Ensure meta title is set by search views

- templates/search/blocks/search_results.html
1. Added page index
2. Removed bold/highlight settings
> DF-248:Make-catalogue-search-results-count-reflect-current-pagination

- sass/etna.scss
- sass/includes/_blog-embed.scss
- sass/includes/_buttons.scss
- sass/includes/_content-block.scss
- sass/includes/_insights.scss
- sass/includes/_jumplinks.scss
- sass/includes/_promoted-item.scss
- sass/includes/_quote.scss
- sass/includes/_record-embed__no-image.scss
- sass/includes/_related-ce-content.scss
- sass/includes/_related-resources.scss
- sass/includes/_section-separator.scss
- sass/includes/_sub-heading.scss
- templates/includes/jumplinks.html
- templates/includes/related-ce-content.html
- templates/insights/blocks/promoted_item.html
- templates/insights/blocks/promoted_list_block.html
- templates/insights/blocks/quote.html
- templates/insights/blocks/section.html
- templates/insights/insights_page.html
Hi @ababic,
Here's the new PR for the updates to the Insights FE. Just give me a shout if you need anything 👍
> UN-145: Implement front end design updates to individual Insight page

- etna/insights/blocks.py
- etna/insights/migrations/0039_alter_insightspage_body.py
- etna/records/templatetags/records_tags.py
- templates/insights/blocks/featured_records.html
Implements further changes to FeaturedRecordsBlock as per discussion on ticket:
https://national-archives.atlassian.net/browse/UN-180
> UN-180: Featured Records component amends

- sass/etna.scss
- sass/includes/_section-image.scss
- templates/blocks/content_image.html
Hi @AshTNA,
This PR amends the image component to span the width of the body. Would it be possible to merge if all's okay? Thank you 👍
> UN-164: Image component

- etna/records/models.py
- etna/records/templatetags/records_tags.py
Fixes the record_url() tag to work for Record objects and dicts
> UN-180: Featured Record component: Fix {% record_url %} issue

- etna/search/views.py
Search results "search term" -> Search results **for** "search term"
> DF-230: Add <title> to search pages (amend)

- etna/records/field_labels.py
Resolves: https://national-archives.atlassian.net/browse/UN-193
> UN-193: Add missing 'title' field name to mappings

- etna/records/transforms.py
Resolves Sentry issue: https://sentry.io/organizations/the-national-archives/issues/3260325174/
> Fix: Transformation function erroring when encountering topic data in a different format

- templates/search/blocks/search_results__list-card--grid.html
- templates/search/blocks/search_results__list-card.html
Hi @ababic 
This completes https://national-archives.atlassian.net/browse/DF-253
Would you be able to review this implementation of Website result URLs? I'm guessing you might have a better way of implementing this.
Thanks :+1:
> DF-253: Website results -  add correct URLS to links

- scripts/src/insights.js
- scripts/src/modules/insights/accordion_functionality/accordion_functionality.js
- scripts/src/modules/insights/accordion_functionality/convert_px_property_to_number.js
- scripts/src/modules/insights/accordion_functionality/scroll_to_active_heading.js
- scripts/src/modules/insights/accordion_functionality/slide_toggle.js
Hi @AshTNA,
Would it be possible to have a look at this PR? It implements the bug fix that we discussed earlier. If all's okay, would it be possible to merge (but don't delete the branch)? Thank you 👍
> UN 197: Insights page mobile menu scrolling issue

- etna/search/tests/fixtures/website_search_highlight.json
- etna/search/tests/fixtures/website_search_insight.json
- etna/search/tests/test_views.py
- etna/search/views.py
- templates/search/blocks/search_results__list-card--grid.html
- templates/search/blocks/search_results__list-card.html
- Contains backend changes to show image for insight and highlight filteraggregations.
@ababic Thanks for the great Idea of showing the Images :)
> DF-199:Website results - add images to results

- templates/insights/insights_page.html
Hi @jamesbiggs,
Would it be possible to merge this is all's okay? Thank you 👍
> Copy change

- sass/includes/_header.scss
- sass/includes/search/_global-search.scss
- scripts/src/modules/search/global-search.js
- templates/includes/header.html
Would it be possible to have a look at this PR? It contains the design changes to the header that we've been discussing recently. I've made a few extra changes to get it working on IE11 (in addition to what we talked about earlier), happy to go through it on a call if that would be easier. Thank you 👍
> DF-222: Redesign header navigation to be a hamburger menu on mobile

- .github/workflows/main.yml
- poetry.lock
- pyproject.toml
> Upgrade black

- sass/includes/_hierarchy-local-nav.scss
- templates/includes/records/hierarchy-local.html
Could you have a look at this PR? It fixes some minor things with the local hierarchy (details in the commit message). Would it be possible to merge if all's okay? Happy to have a call to show you the changes if you'd like. Thank you 👍
> Fix hierarchy local links

- etna/ciim/client.py
- etna/ciim/tests/test_client.py
Make collection, heldby fields to use OR operator for multiple filter values
> DF-333:Update 'Collection' and 'Held by' filters to use 'OR' rather than the default 'AND' operator

- scripts/src/ds-cookie-consent.js
- scripts/src/modules/cookie_consent/data.js
Hi @gtvj,
This PR just adds some additional cookies that Helen said needed to be deleted if cookies are rejected. Would it be possible to merge if all's okay? Thank you 👍
> UN-235: List all GA cookies

- etna/core/middleware.py
- etna/core/tests/test_middleware.py
Related ticket: https://sentry.io/organizations/the-national-archives/issues/3444804473/
> Fix: TypeError: 'NoneType' object does not support item assignment

- etna/collections/models.py
- templates/collections/time_period_explorer_page.html
- templates/collections/topic_explorer_page.html
> Rearrange the feature insights location in the admin and templates

- etna/insights/models.py
- templates/insights/insights_index_page.html
> Fixing duplicated insights

- package-lock.json
- sass/includes/search/_search-filters.scss
- sass/tna-toolkit/_variables.scss
- templates/search/blocks/search_filters.html
> Df 340 refine results by heading typeface is roboto should be supria sans condensed

- scripts/src/catalogue-search.js
- scripts/src/modules/analytics/search/search_result_interaction.js
- templates/search/blocks/search_results.html
- templates/search/blocks/search_results__list-card--grid.html
- templates/search/blocks/search_results__list-card.html
This is the second PR for [DF-274](https://national-archives.atlassian.net/browse/DF-274?atlOrigin=eyJpIjoiMDM3ZWEyZmNjOTY5NGEzZTg3M2YwM2YyNGUxYTU3ZGQiLCJwIjoiaiJ9)
> Add analytics tracking for interactions with search result link

- sass/includes/_breadcrumb.scss
- https://national-archives.atlassian.net/browse/UN-316
- small style change on breadcrumbs
- Check the breadcrumb functionality across different screen sizes
- [ x] Checked things thoroughly myself before handing over to you.
- [ x] Included the ticket number in the PR title to help us keep track of changes
- [ x] Ensured that my PR does not include any irrelevant commits.
- [ x] Waited for all CI jobs to pass before requesting a review.
- [ x] Added/updated tests and documentation where relevant.
> Minor style change on breadcrumbs.

- sass/includes/_header.scss
- templates/includes/header.html
https://national-archives.atlassian.net/browse/UN-294
Added in the search and hamburger icons : menu is now opened via css
Please check the functionality, if possible on a mobile device. There maybe some positioning issues with the icons but please review ands feedback. Thanks
> Un 294 mobile view menu

- templates/insights/insights_index_page.html
(https://national-archives.atlassian.net/browse/UN-334)
Small bug fix for the "new" label on the spotlight card.
> Fix in the HTML logic for new label on spotlight

- templates/collections/time_period_explorer_page.html
- templates/collections/topic_explorer_page.html
(https://national-archives.atlassian.net/browse/UN-308)
Removed the image caption on the spotlights on time period and topic explorer pages.
> UN-308 Bug regarding the image caption displaying

- .github/PULL_REQUEST_TEMPLATE.md
- None
Changed comments as discussed in meeting
Will appear on subsequent PR's
> Updated comments as discussed in meeting

- etna/navigation/models.py
- etna/records/views/choosers.py
- poetry.lock
- pyproject.toml
- <- (https://national-archives.atlassian.net/browse/DF-358) ->
<- Upgrade to Django 4.0.0 compatable with current 3.0.1 wagtail ->
> DF-358-Upgrade to Django 4.0.0

- package-lock.json
- sass/includes/_header.scss
- https://national-archives.atlassian.net/browse/UN-294
<- now targeting mobile navigation via ID
check the mobile navigation. Also check the search functionality to ensure that other checkboxes are displaying correctly.
> checkbox fix for mobile navigation

- templates/insights/insights_index_page.html
(https://national-archives.atlassian.net/browse/UN-272)
Fix to featured insights data-label.
> UN-272 New label analytics

- sass/includes/_card-groups.scss
- sass/includes/_featured-insight.scss
- templates/includes/card-group-secondary-nav.html
- templates/insights/insights_index_page.html
- https://national-archives.atlassian.net/browse/UN-271
I have refactored the html so it is now in the correct order, once merged to develop it should pull together the recent fe and be changes
Please check with the code ispector that all the relevant attributes on links are populating
> Un 271 new stories label front end work refactor

- templates/includes/breadcrumb.html
(https://national-archives.atlassian.net/browse/UN-345)
Added GTM attributes to breadcrumb links
> UN-345 Breadcrumb Analytics

- etna/ciim/constants.py
- etna/search/forms.py
- etna/search/templatetags/search_tags.py
- etna/search/views.py
- templates/search/blocks/search_filters.html
- templates/search/blocks/search_results_hero.html
- templates/search/blocks/search_sort_and_view_options.html
- templates/search/catalogue_search.html
- templates/search/catalogue_search_long_filter_chooser.html
- templates/search/featured_search.html
- templates/search/website_search.html
https://national-archives.atlassian.net/browse/DF-412
- generates html hidden fields for search with unique html id.
As mentioned in the ticket.
> DF-412:disappearing search filter

- templates/search/blocks/search_pagination.html
- templates/search/blocks/search_results__selected-filters.html
- templates/search/catalogue_search_long_filter_chooser.html
- https://national-archives.atlassian.net/browse/DF-378
Double quotes wher e being handled as special characters 
Inspect code changes via github
> DF-378 : unicode double quote fix

- sass/includes/search/_search-landing-buckets.scss
- https://national-archives.atlassian.net/browse/DF-314
padding adjusted for explanatory paragraphs
- Please check layouts visually : mobile / tablet / mobile
> DF-314 : adjusted padding for explanatory paragraphs for search results

- scripts/src/insights-index-page.js
https://national-archives.atlassian.net/browse/UN-372
Added in the data-card-position tag to story titles via scripts/src/insights-index-page.js
Inspect the title links on the stories index page to confirm that the data-card-position tag is populating correctly
> adding in gta tag

- package-lock.json
- poetry.lock
- pyproject.toml
https://national-archives.atlassian.net/browse/UN-337
> UN-377:Restore Django=~4.0, package-lock.json to 0efc

- etna/ciim/constants.py
- etna/search/forms.py
- etna/search/templatetags/search_tags.py
- etna/search/views.py
- templates/search/blocks/search_filters.html
- templates/search/blocks/search_results.html
- templates/search/blocks/search_results__selected-filters.html
- templates/search/blocks/search_results_hero.html
- templates/search/catalogue_search.html
- templates/search/website_search.html
https://national-archives.atlassian.net/browse/DF-430
- Shows error message for invalid date input instead of no results page
- Handles date filter processing which was not previously there before implementing no results.
See the ticket for examples
> DF- 430 no results date validation

- sass/includes/search/_search-buckets.scss
- sass/includes/search/_search-results-hero.scss
- sass/includes/search/_search-results.scss
- sass/includes/search/_search-results__list-card.scss
- sass/includes/search/_search-sort-view.scss
- scripts/src/modules/search/mobile-filter-expander.js
- templates/search/blocks/catalogue_search_buckets.html
- templates/search/blocks/search_results__list-card.html
https://national-archives.atlassian.net/browse/DF-352
Changes to the mobile UI for search functionality
Please check against design and tickets
> DF-352-mobile-ui-changes

- sass/includes/_pagination.scss
- templates/search/blocks/search_pagination.html
https://national-archives.atlassian.net/browse/DF-293
Revised code for pagination element
Check against design
> DF-293 : revised styles and html for new pagination element

- etna/search/views.py
Merge test/staging-feature-1 into test/develop-from-main
> Merge test/staging-feature-1 into test/develop-from-main

- etna/search/views.py
https://national-archives.atlassian.net/browse/DF-436
> DF-436:test/staging-feature-2 to test/develop-from-main

- etna/search/views.py
https://national-archives.atlassian.net/browse/DF-436
> DF-436:test/staging-feature-2 to test/staging

- etna/search/views.py
https://national-archives.atlassian.net/browse/DF-436
> DF-436:test/staging to test/main (#524)

- etna/search/templatetags/search_tags.py
https://national-archives.atlassian.net/browse/DF-458
Handle date filter label exclusions
Scenarios mentioned in the ticket.
> DF-458:Fix for Date filter label when removed, does not return expected search results.

- templates/search/blocks/survey.html
> Un-371 Added images to JS

- etna/search/templatetags/search_tags.py
- etna/search/views.py
- templates/search/blocks/search_results_hero.html
- templates/search/website_search.html
https://national-archives.atlassian.net/browse/DF-424
Return the search title for each search tab.
Navigate to each search tab and view the search title. 
> DF-424:Title for search results

- scripts/src/modules/search/mobile-filter-expander.js
- templates/search/blocks/search_results.html
https://national-archives.atlassian.net/browse/DF-388
adding in the filter value for mobile search ui
Please test using a variety of terms and applying filters
> Df 388 mobile filter value

- sass/includes/_cta-banner-survey.scss
https://national-archives.atlassian.net/browse/UN-445
Hidden CTA survey banner
Make sure there is only one feedback mechanism
> UN-445: BUG Remove repeating feedback mechanism

- scripts/src/modules/search/mobile-filter-expander.js
Removed commented line causing issue with merge to main
> CHORE:removed commented line causing issue with merge to main

- etna/ciim/constants.py
- etna/search/tests/test_forms.py
- sass/includes/search/_search-filters.scss
https://national-archives.atlassian.net/browse/DF-449
Error message styles applied
Please test with incorrect dates entered
> error message for search dates

- sass/includes/_jumplinks.scss
https://national-archives.atlassian.net/browse/UN-448
100vh removed from jumplinks element
Please check the jumplinks behavior
> jumplinks amendment

- etna/ciim/constants.py
- etna/search/tests/test_forms.py
- sass/includes/search/_search-filters.scss
- scripts/src/modules/focus_element_if_found.test.js
https://national-archives.atlassian.net/browse/DF-449
Full. stop added to error message
Please check error message
> DF-449: re style date validation error message

- package-lock.json
https://national-archives.atlassian.net/browse/DF-416
Fix conflict markers
> DF-416:fixed conflict markers

- templates/search/blocks/search_filters.html
https://national-archives.atlassian.net/browse/DF-474
Show search text for all buckets
Navigate through all buckets, view the search text
[DF-474]: https://national-archives.atlassian.net/browse/DF-474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DF-474:Show search text for all buckets

- package-lock.json
- templates/search/blocks/catalogue_search_buckets.html
https://national-archives.atlassian.net/browse/DF-498
Update to id / data-id values
Conduct a search and select Catalogue results
Change to Mobile view using responsive design
Right-click on either the drop-down menu or the update button and select Inspect
Have both the id and data-id been updated to catalogue-search-bucket-mobile?
> updating form id / data-id

- sass/includes/search/_search-landing-buckets.scss
- sass/includes/search/_search-sort-view.scss
- templates/search/website_search.html
- https://national-archives.atlassian.net/browse/DF-488
<- Added in the buckets drop down for website results mobile view
<- Please check behaviour across different screen sizes 
> adding in the buckets drop down for website results on mobile

- templates/search/search.html
https://national-archives.atlassian.net/browse/DF-327
Check commented elements are not rendering
Check code : search.html
> commenting out unused elements

- etna/search/forms.py
https://national-archives.atlassian.net/browse/DF-490
Updated field label
As mentioned in the ticket
> DF-490:Change 'Collection' label to 'Collections'

- package-lock.json
- templates/search/blocks/catalogue_search_buckets.html
https://national-archives.atlassian.net/browse/DF-498
updating id's on the search form
Conduct a search and select Catalogue results
Change to Mobile view using responsive design
Right-click on either the drop-down menu or the update button and select Inspect
Have both the id and data-id been updated to search-bucket-mobile?
> DF-498: Change data ids on search form

- .github/PULL_REQUEST_TEMPLATE.md
- docs/developer-guide/contributing.md
- docs/developer-guide/project-conventions.md
https://national-archives.atlassian.net/browse/DF-484
Document guideline changes
Process to follow
> DF-484:update-project-guidelines

- .github/PULL_REQUEST_TEMPLATE.md
https://national-archives.atlassian.net/browse/DF-484
Removed checkboxes as discussed in meeting.
Process to follow
- select `Squash and merge`
- After merging PR:
- check and arrange to deploy on platform-sh.
- update status on JIRA ticket on deployment.
- update slack on deployment progress of the JIRA ticket once deployed.
> DF-484:Removed checkbox

- .github/dependabot.yml
Using docker file for testing dependabot versioning checks
- none
adding dependabot.yml file -> testing with docker file and enabling dependabot functionality
no idea - maybe monitoring the repo if dependabot shows notifications
- select `Squash and merge`
- After merging PR:
- check and arrange to deploy on platform-sh.
- update …
> test dependabot.yml file

- etna/articles/migrations/0048_add_recordarticlepage_and_pagegalleryimage.py
- etna/articles/models.py
- etna/highlights/migrations/0001_initial.py
- etna/highlights/models.py
- etna/records/fields.py
While our custom `RecordChooserField` works fine for the `Highlight` snippet model; when used on a model that uses revisions (e.g. `RecordArticlePage.record`), the value gets misinterpreted during the serialisation process, and a full string representation of the record ends up as the stored value (e.g. "Record title (IAID)"), which the field isn't designed to handle.
The key change here is the addition of the `value_to_string()`, which is responsible for returning a value suitable for serialisation. Since it's an `iaid` string that is usually stored in the database, it makes sense that the same value also be used as the serialised value.
There are a couple of extra changes here too:
1. I renamed the model field to `RecordField` because the interface shouldn't be a concern for model …
> Fix: RecordChooserField incompatibility with Wagtail's revision framework

- etna/records/views/records.py
- templates/includes/records/hierarchy-global.html
- templates/includes/records/record-cta-panel.html
- templates/includes/records/record-details.html
- templates/includes/records/record-related-content.html
- templates/includes/records/record-related-records.html
- templates/includes/records/record-series-panel.html
- templates/includes/records/record-title.html
- templates/includes/records/taxonomy-tags.html
- templates/records/record_detail.html
- templates/records/record_disambiguation_page.html
https://national-archives.atlassian.net/browse/DF-465
- references to access record class in details page template is via `record` context attribute.
- references to access record class in disambiguation details template is via `record_results_page` context attribute.
As mentioned in the ticket.
- select `Squash and merge`
- After …
> DF-465:record-details-page-to-record

- .github/PULL_REQUEST_TEMPLATE.md
None
Update documentation for before merges - to allow merges after Review Approval by Developer as well.
On next PR
- select `Squash and merge`
- After merging PR:
- check and arrange to deploy on platform-sh.
- update status on JIRA ticket on deployment.
- update slack on deployment progress of the JIRA ticket once deployed.
> CHORE:Update doc for before merges

- etna/core/models/basepage.py
https://national-archives.atlassian.net/browse/UN-451
Changed `"insights"` to `"articles"` in the `basepage.py` `GTM_CONTENT_GROUPS` variable.
Go to `/stories` on your local host, open the console and enter `dataLayer`. This will then show the GTM variables being passed from the back-end. Ensure that contentGroup1 says "Articles". Check this on an article page as well, not just the index page.
- check PR merge tile begins …
> UN-451 - Performance Metrics - Backend tracking requirements update - content group

- .github/PULL_REQUEST_TEMPLATE.md
* Fix weird code-block formatting
* Simplify structure and language
* Move common scenario (merging a feature branch into dev) above the release scenario
* Remove the 'check that merging to develop is okay' line - this should always be okay for approved changes
* Be more specific about where to check / communicate about deployments
> CHORE: Further PULL_REQUEST_TEMPLATE tweaks

- templates/search/blocks/survey.html
https://national-archives.atlassian.net/browse/DF-526
ALT tags added to feedback mechanism icons
Add a human-readable description here
ALT tags added to feedback mechanism icons
Inspect icons in developer tools for Alt attribute please
2. To start a deployment, push the relevant branch to the `platform` …
> alt tags for feedback mechanism

- templates/articles/article_index_page.html
- templates/home/home_page.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-475
`data-component-name` was returning "Featured Story:" on the front-end. It is needed to be "Featured Article".
Navigate to anywhere the "featured story/article" component is used. Inspect element on the "Read" button, and ensure that it says `data-component-name="Featured Article: . . ."`.
2. To …
> UN-475: Bug fix on FE requirements for Featured Article

- etna/analytics/mixins.py
- etna/articles/models.py
- etna/collections/models.py
- etna/core/models/basepage.py
- etna/home/models.py
Ticket URL: https://national-archives.atlassian.net/browse/UN-451
The ask was to change the current "Stories" value that is displayed for page types in the `articles` app, which I did - but, I figured it was also high time to ditch the "Work out the label from the app name" mechanism, as it's simply too clever for it's own good, and doesn't lend itself well to doing things differently in future (we already need to use a different value for record articles)
1. Use the `Create a merge commit` option to preserve the original commit …
> UN-451: Tweak contentgroup1 datalayer label for articles models

- .platform.app.yaml
- fabfile.py
Ticket URL: 
https://national-archives.atlassian.net/browse/UN-411
Remove call to rename_app
As the `insights` folder has been renamed to `articles`, the `rename_app` does not find it, making the call obsolete.
4. …
> UN-411:Remove calls to rename_app post deployment

- sass/includes/search/_search-sort-view.scss
- sass/tna-toolkit/_icon.scss
- sass/tna-toolkit/tna-toolkit.scss
- templates/base.html
- templates/includes/icon.html
- templates/includes/icons/sprites.html
- templates/search/blocks/search_sort_and_view_options.html
- templates/static/images/icons/grid-selected.svg
- templates/static/images/icons/grid.svg
- templates/static/images/icons/list-selected.svg
- templates/static/images/icons/list.svg
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/boards/76?selectedIssue=DF-514
Adds a new icon include to remove need for including icons as background images, which provides better styling control by allowing us to add classes to the svgs.
This also updates the styling of the sort by icons to improve the colours and contrast in HCM (high contrast mode).
Using devtools or another high contrast emulator (or windows high contrast if available) check the sort by icons on a search results page to ensure they are visible and also pass sufficient contrast levels.
- Added/updated tests and documentation where relevant. - n/a
2. Where relevant, include the ticket number in …
> [DF-514] Sort by icons

- config/settings/base.py
- etna/articles/migrations/0047_insights_insight_to_article.py
- etna/articles/models.py
- etna/generic_pages/migrations/0002_streamfield_use_json_field.py
- etna/home/migrations/0014_alter_homepage_body.py
The missing `ol` option on paragraph blocks feels like an oversight. In most cases where a `ul` is suitable, there's no reason why `ol` should not be. So, this PR adds the 'ol' option to `RESTRICTED_RICH_TEXT_FEATURES` so that we have that consistency.
You should be able to see/use the `ol` option in homepage, general page and article content. 
2. To start a …
> CHORE: Improve Rich Text option consistency

- sass/includes/_header.scss
- templates/includes/header.html
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/boards/76?selectedIssue=DF-515
This MR does two things:
- Adds a SR-only label for the mobile menu toggle to ensure screenreader users understand what it does
- Refines the mobile menu toggle styling by using classes on the checkbox/label and following BEM conventions, to help style the components independently from each other and reduce reliance on styling the tags themselves (e.g. span, input etc).
- Updates input/label to make sure the mobile menu toggle is accessible via keyboard
Inspect the mobile menu button and/or test with a screenreader to confirm the SR label is read aloud
Test mobile & desktop nav styles across mobile, tablet & desktop to make sure everything works & looks as expected (compare with …
> [DF-515] SR-only mobile menu label

- templates/base.html
- templates/search/blocks/search_results.html
- templates/search/catalogue_search.html
- templates/search/website_search.html
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/boards/76?selectedIssue=DF-522
Adds the number of search results to the page title so this is read aloud first for screenreader users. 
Adds a 'skip to results' link at the top of the page, directly after the 'skip to main content' link. This enables users to skip past the filters and go straight to the results.
Perform a search and view catalogue or website results, see that the number of results is reflected in the page title.
Using the tab key, after submitting a search tab to and click the 'skip to results' link and see focus jumps directly to the list of results.
2. Where relevant, include the ticket number in …
> [DF-522] Announce number of search results on submit

- sass/includes/_transcription.scss
- templates/articles/record_article_page.html
- templates/includes/image_gallery.html
- templates/includes/record-matters.html
- templates/includes/record-revealed.html
Ticket URL:  [here](https://national-archives.atlassian.net/browse/UN-387)
This PR addresses;
- "record matters" Truncates text (was based on words vs char's), hides read more button if it's less than 50 char's
- Standfirst is shown in intro, the PR changing this pattern didn't alter this field.
- Small changes to image max-size larger monitors to prevent layout shift.
- Add caption for images.
- Use "Stories from the collection" for the record-matters header.
Screenshots of majority of changes: https://national-archives.atlassian.net/browse/UN-387?focusedCommentId=41516
2. Where relevant, include the ticket number in commit title, e.g. …
> Update record article page from internal review

- templates/search/blocks/search_landing_hero.html
https://national-archives.atlassian.net/browse/DF-516
I have updated the label to reflect the input field
Please inspect the code to confirm the changes
4. Update the status on the corresponding Jira ticket (where …
> DF-516 - updating label for search input

- .github/workflows/main.yml
- .platform.app.yaml
- Dockerfile
- docs/developer-guide/project-conventions.md
Ticket URL: https://national-archives.atlassian.net/browse/UN-478
Upgrading Python from 3.9 to 3.10
Re-build your Docker containers so that Python is upgraded to 3.10. Then check that it has been done correctly by running `python -V` inside your container.
Then ensure that the site is working locally, tests can be run, and there are no major issues.
2. To start a …
> UN-478: Upgrade Python to 3.10

- sass/includes/search/_search-filters.scss
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/boards/76?selectedIssue=DF-517
Add a lighter bg colour to the sidebar filter section to increase contrast between bg and 'see more' link.
Run an axe accessibility test or other automated a11y test on search results and see that the 'see more' link no longer returns a contrast error.
Alternatively use a [colour contrast checker](https://webaim.org/resources/contrastchecker/) to test link colour against the updated background colour. …
> [DF-517] Update search filters background colour

- sass/includes/search/_search-results-hero.scss
- sass/includes/search/_search-sort-view.scss
Ticket URL: https://national-archives.atlassian.net/browse/DF-520
Spacing adjustments for submit buttons
Please check the search forms on mobile view
- [x ] Ensured that PR includes only commits relevant to the ticket.
3. Update the appropriate Slack channel when the deployment is …
> DF-520-Spacing adjustment on mobile/tablet view

- sass/includes/search/_search-results.scss
Ticket URL:(https://national-archives.atlassian.net/browse/DF-521)
The Filters button now displays consistently across viewports
Please test the behavior of the filters button across viewports
4. Update the status …
> DF-521-adjusting-breakpoint-for-filters-button

- templates/search/blocks/catalogue_search_buckets.html
- templates/search/blocks/search_landing_buckets.html
- templates/search/blocks/website_search_buckets.html
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/boards/76?selectedIssue=DF-557
- Updates search bucket aria-label to 'Record categories' from 'Result categories' for consistency with labelling.
- Updates all search buckets to use `<nav>` element for consistency and improved UX.
Navigate to search landing page, inspect search buckets and see search buckets have been updated to use <nav> element.
Navigate to each search result page (all, catalogue and website), inspect the search buckets and see the aria-label is updated to 'Record categories'.
- [ x Ensured that PR includes only commits relevant to the ticket.
2. Where relevant, include the ticket number in commit …
> [DF-557] Update search buckets with consistent labelling

- templates/includes/footer.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-497
Updated relevant footer links to include `www.` as some of them were defaulting to a redirect on www.nationalarchives.gov.uk and some were going to an error page, due to a lack of a redirect on www.nationalarchives.gov.uk.
Scroll to the footer link, click them - ensure they go to the correct destination and don't give any errors or default to redirecting
1. Post to the …
> UN-497: Update footer links

- templates/articles/article_index_page.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-484
Added `data-link="Read"` to Featured Article
Check that `data-link="Read"` has been added to the Featured Article button in the HTML
4. Update the …
> UN-484: Add data-link="Read" to Featured Article

- sass/includes/search/_search-results.scss
- templates/search/blocks/search_results__selected-filters.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-560
- Hides the SR-only filter heading when there are no active filters.
- Hides the wrapper div for active filters if empty.
- Updates spacing
Inspect results heading when no filters are active and see that the title and wrapper div is hidden.
2. To start a deployment, push the relevant branch to the …
> [DF-560] 'Selected filters' SR-only heading

- templates/includes/header.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-554
Removing the checkbox from the tabbing order
As a keyboard or screen reader user 
I want to be able to tab through interactive elements of a page
So I can select or interact with them.
Please check via screen reader
3. …
> DF-554-removing checkbox from tabbing order

- etna/records/views/records.py
Ticket URL: https://national-archives.atlassian.net/browse/DF-573
Added `meta_title` context to view.
View the record details page and observe the title.
4. Update the status on the corresponding Jira ticket (where …
> DF-573:Fix Record details page title

- sass/includes/search/_search-sort-view.scss
- templates/search/blocks/catalogue_search_buckets.html
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/boards/76?selectedIssue=DF-563
Increase default height of select box to a minimum of 44px & some smaller styling refinements.
Check search results page on mobile & review the select box styling changes.
3. …
> [DF-563] 'Show results from' filter select box styles

- templates/includes/results-options.html
- templates/search/blocks/catalogue_search_buckets.html
- templates/search/blocks/search_filters.html
- templates/search/blocks/search_results_hero.html
- templates/search/blocks/search_sort_and_view_options.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-577
Removes all empty action attributes as they are causing validation errors and not required.
- Inspect element on forms which have been updated & see the action attribute has been removed
- Test forms to ensure they are working correctly
2. To start a deployment, push the relevant branch to the …
> [DF-577] Remove empty action attributes from form elements

- sass/includes/search/_search-sort-view.scss
https://national-archives.atlassian.net/browse/DF-591
Adjusting the width of the Sort by dropdown on search results page
Please check the layout of the Sort by dropdown on search results page
> DF-591-width adjustment on Sort By drop down

- templates/search/blocks/search_results__selected-filters.html
https://national-archives.atlassian.net/browse/DF-593
Adjusted logic to show the remove all filters link in the search results
Perform a search, apply some filters, ensure that the 'Remove all filters' link displays and is functional.
> DF-593-logic change for the 'remove all filters' link on search results

- etna/images/migrations/0006_remove_customimage_transcription_language_and_more.py
- etna/images/models.py
Quick change for some values on the previous UN-498 PR!
> UN-498: Made adjustments to `models` and the original migration

- templates/includes/records/hierarchy-global.html
Ticket URLs:
- https://national-archives.atlassian.net/browse/DF-580
- https://national-archives.atlassian.net/browse/DF-581
Adds aria-labelledby attributes to short & long hierarchy navs to make sure they are labelled correctly for SR users
- Navigate to catalogue detail page 
- Tab to the hierarchy navigation (both short & detailed)
- SR should read its title aloud automatically once focus is on the nav
- Short hierarchy should read "Catalogue location at a glance" 
- Detailed hierarchy nav should read "Detailed catalogue location"
1. Use the `Create a merge commit` option to preserve …
> [580] [581] Aria attributes for hierarchy navigation elements

- .github/workflows/cd.yml
DISCUSS!
1. Create `SLACK_WEBHOOK` secret using [GitHub Action's Secret](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-a-repository). You can [generate a Slack incoming webhook token from here](https://slack.com/apps/A0F7XDUAZ-incoming-webhooks). 
2. Create a new Platform.sh user specifically for deployment (very convenient if you need to change values for security reasons), and generate/find the relevant `PLATFORM_CLI_TOKEN` and `PLATFORM_SSH_KEY` values 
3. A GitHub user with admin-level account access to populate the necessary 'secrets' values in the GitHub project settings:
- `SLACK_WEBHOOK` (from step 1)
- `PLATFORM_PROJECT_ID` (a fixed value that will likely never change)
- …
> Continuous Delivery

- .github/workflows/cd.yml
Remove extra test- on test-javascript
> CHORE: CD fixes

- poetry.lock
Ran `poetry update` to update the lock file.
Check that everything is working as expected, and that everything is updated :)
> CHORE: Update all dependencies in Poetry

- poetry.lock
Ticket URL: https://national-archives.atlassian.net/browse/UN-523
Ran `poetry update` to get the latest versions of our packages
> UN-523: Wagtail 4.2.1 -> 4.2.2

- templates/collections/time_period_explorer_page.html
- templates/collections/topic_explorer_page.html
Removed FEATURE_RELATED_ARTICLE_ON_EXPLORE_PAGES
> FIX: Remove FEATURE_RELATED_ARTICLE_ON_EXPLORE_PAGES

- etna/images/migrations/0007_customimage_custom_sensitive_image_warning_and_more.py
- lint-requirements.txt
Updated `lint-requirements.txt` to allow for formatting dependency updates
> CHORE: Update lint requirements file

- templates/base.html
Ticket URL: N/a
This change adds back the original wagtail user bar; following official docs here: https://docs.wagtail.org/en/stable/topics/writing_templates.html
log into the admin, and then view any page on the FE and you will see a the menu icon in the bottom right.
> Add wagtail userbar

- templates/includes/records/archive-additional-resources.html
- templates/includes/records/archive-collections.html
- templates/includes/records/archive-description.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-643
1. resolves links from summary
2. removes links from fax field
3. resolves selected year dropdown link for "no year" for Accessions
> DF-643:Archive details resolve links

- templates/articles/article_index_page.html
- templates/includes/article-spotlight.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-555
Removed `role="link"` from NEW label
n/a
> UN-555: Featured Article "New" label is marked with a `role="link"` attribute

- sass/includes/_related-resources.scss
- sass/includes/_variables.scss
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-632
Updates styles for related resource cards to match new designs.
Review story page with related resources and see that the new designs have been added.
> [UN-632] Read more / related resources styling

- templates/articles/article_page.html
Ticket URL: N/A
Forgot to change the variable name in the HTML when changing name in base.py. This is to fix that.
> Fix: Updated variable name in HTML

- sass/includes/_media-embed.scss
- sass/includes/_variables.scss
- templates/media/blocks/media-block--embed.html
- templates/media/blocks/media-block.html
- templates/static/images/icons/chevron-down.svg
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-570
Updating transcript arrow, background position and heading weight
Check the audio player on the Maud Allen post (Locally avaliable using staging data at http://localhost:8000/stories/maud-allan/)
> UN-570: Updating transcript arrow, background position and heading weight

- templates/collections/topic_explorer_page.html
- templates/includes/related-articles-highlight-cards.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-661
Updated topic/time period pages to use featured record article
Go onto a topic/time period page (e.g. British State and Citizens) and look at the record revealed section. Add/remove a featured record article and ensure it looks as designed
> UN-661: Featured record article on Topic/Time periods

- sass/includes/_utilities.scss
Updating the margin utility from PX to REM values as defined in design system:
https://www.figma.com/file/uo8YY98lLws8E1HEfpdn5X/TNA-Etna---Design-system?type=design&node-id=157%3A3851&t=eIC3zAqGHEUxjDXH-1
> [Design system sync] Updating margin util to use rem

- sass/includes/_record-crosslink-panel.scss
Ticket URL: NA
Fix undefined css var
``
Login into develop, the above error should not show.
> CHORE:Fix undefined css var

- sass/includes/_hero-image.scss
- sass/includes/_highlight-gallery.scss
3c932f23 UN-678: Updated Highlight Gallery font colour (#953)
> Release 6.2.1 into main

- templates/records/blocks/record_links_block.html
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-595
Adding data attrubute tags to the anchor link of record-links
Inspect the anchor link
> UN-595: Adding analytics tags to record-links

- templates/articles/blocks/promoted_pages.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-526
Adding tracking data attributes to promoted pages component
> UN-526: Adding tracking data attributes to promoted pages component

- templates/collections/time_period_explorer_page.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-661
As commit history shows
> UN-661: Fix for Time Period pages

- templates/records/blocks/record_links_block.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-692
Changed text from "FROM OUR COLLECTION:" to "IN THE CATALOGUE:"
> UN-692: Changed text from "FROM OUR COLLECTION:" to "IN THE CATALOGUE:"

- sass/includes/search/_search-results__list-card.scss
Ticket URL: https://national-archives.atlassian.net/browse/DF-657
border changes and limiting width's of Headings and descriptions
Perform a search, check results layout in list and grid views
> borders and width

- sass/includes/_hierarchy-global-nav.scss
- sass/includes/_record-crosslink-panel.scss
- sass/includes/_record-cta-panel.scss
- sass/includes/_record-details.scss
- sass/includes/_record-series-panel.scss
- templates/records/record_detail.html
[Ticket DF-705: Details page tidy up](https://national-archives.atlassian.net/browse/DF-705?atlOrigin=eyJpIjoiY2E0M2UxNzM2YWUwNDZmNGEzODAwMWYzMTY5YjAyMWYiLCJwIjoiaiJ9)
1. Changed links from black to standard link blue following some colour issues from global changes. 
2. Reset visited link states for the page for MVP. 
3. Darkened the striped table row grey in the record description.
4. Amended the crosslink panel border to bound the entire box rather than just the left border (also changing the border to yellow rather than transparent).
5. Removed the related records, related content and taxonomy content for MVP whilst they aren't fully functional.
6. Changed the visual separating left hand border for the visual hierarchy to yellow from transparent to improve the appearance on default …
> DF-705: Details page tidy-up

- sass/includes/_highlight-intro.scss
Ticket URL: https://national-archives.atlassian.net/browse/UN-699
Updated breakpoints where colour is changed, and the colour variable that is used
Check a topic/time period page, such as http://localhost:8000/explore-the-collection/explore-by-time-period/georgians/ and check that the intro matches the design https://www.figma.com/file/uo8YY98lLws8E1HEfpdn5X/TNA-Etna---Design-system?type=design&node-id=1145-13897&t=fNN8BnQu8GWiyNFB-0 at the different breakpoints
> UN-699: Topic and Time period intro colour

- scripts/src/modules/analytics/record_tracking/image_gallery_tracking.js
- scripts/src/modules/record-matter.js
Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-684 and https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-669
Updates the event names to make sure they are consistent with requirements.
Test datalayer submission and see that the correct event names are being submitted for both translate/transcription buttons and also the expand accordion button on record revealed page.
> [UN-684 & UN-669] Update event names

- sass/includes/_card-groups.scss
- templates/articles/article_index_page.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-688
Updated card styles to match the designs
Check card styles match current designs
> UN-688: THE STORY OF and RECORD REVEALED styling

- sass/includes/search/_search-results__list-card.scss
Ticket URL: https://national-archives.atlassian.net/browse/DF-706
Layout changes for search results, please see ticket for details
Perform a search, check the layout on the catalogue tab 
> DF-706 : layout improvements for search results

- templates/includes/record-revealed.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-651
Updated featured record article component to use tracking
> UN-651: FIX Featured record article tracking

- package-lock.json
- package.json
Updated packages in need of updates as highlighted by dependabot:
- `sass` 1.62.1 -> 1.63.3
- `webpack` 5.84.1 -> 5.86.0
- `babel/preset-env` 7.22.4 -> 7.22.5
- `webpack-cli` 5.1.1 -> 5.1.4
- `babel/core` 7.22.1 -> 7.22.5
> CHORE: Update JS packages

- docs/features/feedback-mechanism.md
- mkdocs.yml
Adds documentation for the Feedback Mechanism to explain a bit more about how it works and the roles of the various components involved.
@TNA-Allan and @jamesbiggs this information is for you, so please comment if you find anything unclear.
> Add documentation for the feedback mechanism

- templates/includes/highlights-gallery.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-724
Added link to record reference in Highlight Gallery
http://localhost:8000/explore-the-collection/explore-by-topic/migration-and-citizenship/coming-to-britain/
Each record reference should have a link to the record
> UN-724: Added link to record reference in Highlight Gallery

- sass/includes/search/_search-results__list-card.scss
Ticket URL: https://national-archives.atlassian.net/browse/DF-657
Height adjustment for search results
Perform a search, check layout of search results
> DF-657 height fix for search results

- templates/includes/records/hierarchy-global.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-699
Added Archive link for the record details page - missing from The records held at - hierarchy
Open a record details page http://127.0.0.1:8000/catalogue/id/C11184/
Click on the link near "This record is held at" 
The Archive details page http://127.0.0.1:8000/catalogue/id/A13530124/ should show
> DF-699:Fix Update archive link at The records held at - hierarchy

- sass/includes/_related-content.scss
- templates/articles/article_page.html
- templates/articles/blocks/promoted_pages.html
Add a human-readable description here
> UN - 710 Added modifier to remove border on shared class

- templates/articles/blocks/promoted_pages.html
Ticket URL: [Link to ticket](https://national-archives.atlassian.net/browse/UN-722)
Added modifier and placed content in container
Page to test: /explore-the-collection/list-of-suffragettes-arrested-from-1906-1914/
> UN - 722 - Reduced the oversized promoted pages component 

- templates/articles/blocks/promoted_list_block.html
Ticket URL: https://national-archives.atlassian.net/browse/UN-719
Updated link list analytics on Stories pages
http://localhost:8000/stories/ormonde-almanzora-windrush/
> UN-719: Link list analytics

- sass/includes/_transcription.scss
Ticket URL: [Ticket UN 730](https://national-archives.atlassian.net/browse/UN-730)
Added container and text align (center) for gallery heading 
[Local link to test](http://127.0.0.1:8000/admin/pages/211/edit/preview/?mode=)
> UN 730 record revealed image gallery heading styling

- .github/workflows/deploy-docs.yml
Ticket URL:NA
Fix [issue ](https://github.com/nationalarchives/ds-wagtail/actions/runs/5342791389/jobs/9685387454) which is due to incompatible version of python
Deploy docs CD process runs without errors
> CHORE:Fix uncompatible python version in deploy docs

- etna/records/models.py
- etna/records/tests/test_blocks.py
- etna/records/tests/test_models.py
- etna/records/tests/test_templatetags.py
- templates/includes/card-group-record-summary-no-image.html
- templates/records/record_disambiguation_page.html
https://national-archives.atlassian.net/browse/DF-731
> DF-731: Use the 'catalogue reference' url for records by default

- etna/articles/models.py
Ticket URL: [UN-675]
Ordered all pages in the Discover all stories section by first published date
[UN-675]: https://national-archives.atlassian.net/browse/UN-675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UN-675: Added filter to order Stories Landing page by first published date

- etna/feedback/templates/feedback/includes/prompt.html
- etna/feedback/templates/feedback/widgets/response_submit_button.html
- etna/feedback/templates/feedback/widgets/response_submit_button_list.html
- sass/includes/_feedback.scss
Ticket URL: https://national-archives.atlassian.net/browse/DF-726
Adds styling for the latest version of the feedback widget
Review feedback widget locally on any page :)
> [DF-726] Feedback mechanism v2 FE styling

- etna/feedback/templates/feedback/includes/prompt.html
- etna/feedback/templates/feedback/widgets/response_submit_button.html
- sass/includes/_feedback.scss
- scripts/src/feedback-tracking.js
- scripts/src/modules/analytics/feedback_tracking/feedback_widget_tracking.js
- templates/base.html
- webpack.config.js
Ticket URL: https://national-archives.atlassian.net/browse/DF-712
Adds tracking for new feedback widget as outlined in https://national-archives.atlassian.net/browse/DF-712
Test widget locally with various combinations of comment/no comment and positive/negative vote, then check the datalayer after submitting a response to make sure the values match the submitted response.
> [DF-712] Feedback mechanism tracking

- scripts/src/modules/analytics/feedback_tracking/feedback_widget_tracking.js
Ticket URL: https://national-archives.atlassian.net/browse/DF-712
js change to call the correct function
Check to ensure that feedback responses are being pushed to the dataLayer
> DF-712-tracking when a user leaves feedback

- sass/includes/search/_search-results__list-card.scss
- templates/search/blocks/search_results__list-card--grid.html
- templates/search/blocks/search_results__list-card.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-657
also covers  :
https://national-archives.atlassian.net/browse/DF-706
https://national-archives.atlassian.net/browse/DF-730
Improvements to the layout and semantic mark up for the search result pages
Perform a search and check the layout on list and grid views and across viewports
> DF-730 search results improvements

- package-lock.json
- package.json
Updated
webpack: 5.86.0 -> 5.88.0
sass: 1.63.3 -> 1.63.6
> CHORE: JS package updates

- poetry.lock
- pyproject.toml
Ticket URL: https://national-archives.atlassian.net/browse/UN-762
• Updating platformdirs (3.5.3 -> 3.8.0)
• Updating redis (4.5.5 -> 4.6.0)
• Updating setuptools (67.8.0 -> 68.0.0)
• Updating wagtail (5.0.1 -> 5.0.2)
• Updating django-redis (5.2.0 -> 5.3.0)
• Updating mkdocs-material (9.1.15 -> 9.1.17)
• Updating sentry-sdk (1.25.1 -> 1.26.0)
> UN-762: Poetry update

- sass/tna-toolkit/tna-toolkit.scss
- templates/base.html
Ticket URL: [UN 743](https://national-archives.atlassian.net/browse/UN-743)
Added a min-width for the body so it doesn't squash on very small mobile devices
Can be viewed on any pages
> UN 743 minimum viewport width

- sass/includes/_highlight-gallery.scss
Ticket URL: [UN - 753 ](https://national-archives.atlassian.net/browse/UN-753)
Removed the text-decoration for highlight gallery links
[Page to review](http://127.0.0.1:8000/explore-the-collection/explore-by-time-period/medieval/domesday/)
> UN - 753 Removed underline for links in highlight gallery

- sass/includes/_promoted-pages.scss
Ticket URL: [UN 758](https://national-archives.atlassian.net/browse/UN-758)
Added rule to include links with no pseudo states to use the colour black
Check the blogs and podcasts section
[To test](http://127.0.0.1:8000/explore-the-collection/letter-by-the-women-workers-at-fords-of-dagenham/)
> UN-758 Added the & to include link with no pseudo states

- sass/includes/_generic-intro.scss
Ticket URL: [UN - 788](https://national-archives.atlassian.net/browse/UN-788)
Increased the column width for the title
Create a focused article page and include a long title 
> UN 788 focused article   title text alignment and spacing

- sass/includes/_featured-link.scss
Ticket URL: [UN 763](https://national-archives.atlassian.net/browse/UN-763)
Add a human-readable description here
[Page to test](http://127.0.0.1:8000/stories/festival-of-britain/)
> UN 763 featured link on stories   styling update to en dash

- package-lock.json
- package.json
- sass/etna.scss
- templates/includes/highlight-intro.html
This is to introduce the use of reusable components, starting with the hero (a.k.a. "highlight intro" as it is currently named).
Topic pages such as `/explore-the-collection/explore-by-topic/international-trade-and-affairs/` should have the new hero banner which should be nearly identical to the existing banner but with fewer layout issues and sets us up to start including more components.
> Initial concept of reusable components

- sass/includes/_image-block.scss
Ticket URL: [UN - 765](https://national-archives.atlassian.net/browse/UN-765)
Added object fit cover to fix aspect ratio and to fill the container
Observe the images in the content part of the image block component 
[Page to test](http://127.0.0.1:8000/stories/alice-hawkins/)
> UN - 765 Added object cover to fill container and fix aspect ration

- sass/includes/search/_featured-search.scss
Ticket URL: https://national-archives.atlassian.net/browse/DF-748
Increasing contrast on dotted line in All Results
Perform a search, check the All results tab
> contrast change for dotted line

- sass/includes/search/_search-results__list-card.scss
Ticket URL: https://national-archives.atlassian.net/browse/DF-750
Adjusted padding for search results on small mobile view
Please check the search results layout on mobile views
> DF-750 padding adjustment for small mobile

- sass/includes/search/_search-landing-buckets.scss
Ticket URL: https://national-archives.atlassian.net/browse/DF-744
adjusted padding on search landing page
Check layout of search landing page
> DF-744 padding adjustment

- sass/etna.scss
Completely remove reference to new toolkit
> CHORE: Remove all reference to toolkit

- scripts/src/modules/analytics/search/search_filters_tracking.js
Ticket URL: (https://national-archives.atlassian.net/browse/DF-590
sending Filters to the dataLayer
Perform a search and filter by opening date / closing date / both dates / no dates and inspect the dataLayer via the console to see that values are bing pushed correctly.
> DF-590: Record opening date tracking update

- etna/ciim/constants.py
- etna/search/forms.py
- etna/search/tests/test_views.py
- etna/search/utils.py
- etna/search/views.py
- templates/search/blocks/native_website_result--grid.html
- templates/search/featured_search.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-753
Now that we are utilising Wagtail's built-in search mechanisms for website results, we must update the 'All results' view to show a summary of the results.
> DF-753: Surface website results on 'All results' page [BE]

- etna/core/widgets.py
- templates/search/blocks/search_filters.html
Re-added missing filters to the search form
> CHORE: FIX Re-add removed filters

- sass/includes/_feedback.scss
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/issues/DF-742
Adjusted the width of the feedback mechanism and the buttons contained within.
Log in to the backend and add up to five feedback options, publish and check layout across viewports.
> feedback mech option layouts

- sass/includes/_pagination.scss
Ticket URL: https://national-archives.atlassian.net/browse/DF-685
Adjusting the vertical position of the 'Next' and 'Previous' links in the pagination
Perform a search, check the vertical position of the 'Next' and 'Previous' links in the pagination.
> DF-685 pagination fixes

- package-lock.json
- package.json
Updated jest and jest-environment-jsdom to 29.6.2
> CHORE: JavaScript package updates

- .gitignore
- bash/run-dev.sh
- config/settings/dev.py
- docker-compose.yml
- docs/developer-guide/fetching-data.md
- fabfile.py
- package.json
- Moved media storage to a Docker volume
- CSS and JS development compilation doesn't start automatically unless `AUTO_START_SERVER=true` for faster startup time
- Updated docs for pulling media from platform.sh
> Local development permissions

- templates/includes/header.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-792
Pages on `/search` and `/catalogue` only show a "Search" menu item.
> DF-792: Hide site navigation when on search or catalogue

- package-lock.json
- package.json
- sass/includes/_mixins.scss
Fix the issue addressed in https://github.com/nationalarchives/ds-wagtail/pull/1261 that occurred with SASS >=1.65
> Update sass to v1.65

- package-lock.json
- package.json
- poetry.lock
- pyproject.toml
**Poetry:**
wagtail 5.1 -> 5.1.1
coverage 7.2.7 -> 7.3
django-debug-toolbar 4.1 -> 4.2
**NPM:**
babel/core 7.22.9 -> 7.22.10
babel/preset-env 7.22.9 -> 7.22.10
sass 1.64.2 -> 1.65.1
> CHORE: Package updates

- templates/includes/card-group-record-summary-no-image.html
Ticket URL: [DF-795]
Made for loop start from 0, and removed pre-existing data attributes
[DF-795]: https://national-archives.atlassian.net/browse/DF-795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DF-795: FIX for data attributes

- templates/includes/header.html
> Fix search menu item (#1279)

- sass/includes/_record-matters.scss
Adjusted display types for record revealed buttons.
Please check the Record revealed pages are displaying correctly across viewports
> adjustments for buttons on record revealed pages

- docs/developer-guide/docker.md
- docs/developer-guide/project-conventions.md
- docs/features/analytics-tracking.md
- mkdocs.yml
Adds a page to work on for analytics/tracking documentation around the project.
Updates a few other pages which were slightly dated, such as the JS/CSS section.
> CHORE: Analytics + tracking documentation

- .github/workflows/_tests.yml
- .github/workflows/run_codecov.yml
Updates some missing pieces from the codecov CI, removes from tests.yml
> CHORE: Update Codecov CI

- sass/includes/_filters.scss
A hotfix for now till we can resolve why the css did not compile with the images referenced.
Add a human-readable description here
> Comment out toggle svgs which was causing a deployment issue

- scripts/src/modules/analytics/search/search_sort_filters_tracking.js
- templates/search/blocks/search_filters.html
- templates/search/blocks/search_sort_and_view_options.html
Ticket URL: [DF-759]
Same PR as previous (https://github.com/nationalarchives/ds-wagtail/pull/1371) - just added a few more fixes!
[DF-759]: https://national-archives.atlassian.net/browse/DF-759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DF-759: FIX Rebuild event sort filter

- etna/authors/models.py
Ticket URL: [UN-806]
Added bulletpoint and numbered lists to Author summary
Edit summary on Author page
[UN-806]: https://national-archives.atlassian.net/browse/UN-806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UN-806: Added bulletpoint and numbered lists to Author summary

- templates/search/blocks/search_filters.html
Ticket URL: https://national-archives.atlassian.net/browse/DF-821
Check text under date filters
Check text under date filters
> DF-821-text-change-for-date-filters

- templates/includes/whats-on-listing.html
- templates/whatson/whats_on_page.html
This is just an advance move in preparation for https://github.com/nationalarchives/ds-wagtail/pull/1404, and to prevent too many merge conflicts in the mean time.
Make sure the what's on listing displays exactly as it did before these changes were applied.
> Move whats on listing to an include

- sass/etna.scss
- templates/articles/focused_article_page.html
Increase size of introduction paragraph on articles and increase column width to make more prominent.
https://national-archives.atlassian.net/browse/UN-815?focusedCommentId=59554
> Tweak introduction text on articles

- templates/articles/focused_article_page.html
https://national-archives.atlassian.net/browse/UN-814
Analytical data added to author links in focused article pages
> Add tracking to author links in focused articles

- etna/whatson/models.py
- sass/etna.scss
- sass/includes/_event-card-listing.scss
- sass/includes/_featured-card.scss
- sass/includes/_full-width-header.scss
- sass/includes/_listing-info.scss
- templates/includes/whats-on-active-filters.html
- templates/includes/whats-on-listing.html
- templates/whatson/whats_on_page.html
Ticket URL: none currently
Styling amendments for whats on listing and ensure the 'clear filters' works with JavaScript
- Refactor the offset for the filters so it can update if the event card is added or removed by the JavaScript
- Show the number of results below the event card when there are no filters applied. In this scenario do not include the featured event in the total
- Once filters are applied, show the total results above the featured event card, and include the featured event card in the total.
- If there are totally no events at all in the database, show a message when the page loads (hopefully this is never seen)
- Added aria-live="polite" to the events listing
Follow …
> Whats on landing tidy up

- sass/etna.scss
- sass/includes/_event-details-banner.scss
- sass/includes/_event-hero.scss
- sass/includes/_event-meta.scss
- sass/includes/_event-tags.scss
- sass/includes/_people.scss
- templates/includes/event_hero.html
- templates/includes/whats-on-listing.html
- templates/whatson/event_page.html
Ticket URL: TBC
Updates event page with various small tweaks and refinements to better align with figma designs
Note: I've kept the icons in the event details banner (below the hero) the same dark pink accent colour, rather than the grey in the designs, to maintain sufficient contrast.
Local preview
> Event page styling refinements (FE)

- sass/includes/_event-meta.scss
- sass/includes/_featured-card.scss
- templates/components/event_tags.html
- templates/includes/event_hero.html
- templates/whatson/event_page.html
Ticket URL: https://national-archives.atlassian.net/browse/DSWO-46
Addresses AJ's feedback following review of the What's On landing page and Event page.
Note: I haven't addressed the breadcrumbs comment, as this probably needs some further design consideration. From local testing the position of the breadcrumbs on the event hero isn't too far from the whats on page - perhaps we need to user test before changing the design?
**Event page feedback**
* The main content ideally needs to be in an `<article>` element and the "Need to know" box should be marked up as an `<aside>` within it. Similarly, the hero (excluding the breadcrumbs) should be a `<header>` element.
* There are already helper classes for the aside which could remove all need for custom CSS in the “Need to know” box:
* The …
> [DSWO-46] Internal feedback adjustments

- scripts/src/modules/analytics/search/search_result_interaction.js
Fix for JS error in console on https://develop-sr3snxi-rasrzs7pi6sd4.uk-1.platformsh.site/search/catalogue/?filter_keyword=royal&covering_date_from_0=&covering_date_from_1=&covering_date_from_2=&covering_date_to_0=&covering_date_to_1=&covering_date_to_2=&opening_start_date_0=&opening_start_date_1=&opening_start_date_2=2000&opening_end_date_0=&opening_end_date_1=&opening_end_date_2=1999&q=ufos&sort_by=&sort_order=asc&group=tna
> Fix JS error

- sass/etna.scss
- sass/includes/_event-meta.scss
- sass/includes/_event-tags.scss
- sass/includes/_exhibition-hero.scss
- sass/includes/_meta-details-banner.scss
- sass/includes/_record-crosslink-panel.scss
- scripts/src/modules/search/mobile-filter-expander-enhanced.js
- templates/components/event_tags.html
- templates/includes/exhibition_hero.html
- templates/includes/meta-banner.html
- templates/search/blocks/search_results.html
- templates/whatson/event_page.html
- templates/whatson/exhibition_page.html
Ticket URL: NA
Sync etna-rosetta with latest changes from develop
> CHORE: sync etna rosetta 281123

- .github/workflows/platformsh-cd-etna-rosetta.yml
Ticket URL: NA
Add CD to etna-rosetta - branch, environment
On code merges to etna-rosetta, it should run tests and trigger deployment to etna-rosetta
> CHORE:add cd for etna-rosetta

- templates/search/featured_search.html
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/issues/DF-828
Copy changes and section headings.
Check that Headings and labels are as listed in Jira ticket
> New labels and section headings for all results.

- templates/search/catalogue_search.html
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/issues/DF-833
Conditional logic to change the `<p class="search-results__explainer">` element depending on which bucket is chosen.
Check the helper text for each bucket in catalogue results
> DF-833 Improvements to bucket labels

- templates/search/blocks/search_sort_and_view_options.html
- templates/search/catalogue_search.html
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/issues/DF-833
removing duplicate text
check pages
> DF=833-Fix/improvements to bucket labels

- sass/includes/search/_catalogue-search-grid.scss
- sass/includes/search/_search-results-hero.scss
- sass/includes/search/_search-results__list-card.scss
- sass/tna-toolkit/bootstrap/_grid.scss
- templates/base.html
- templates/search/blocks/catalogue_search_buckets.html
- templates/search/blocks/search_results_hero.html
- templates/search/blocks/search_sort_and_view_options.html
- templates/search/catalogue_search.html
- templates/search/featured_search.html
- templates/search/native_website_search.html
Ticket URL: https://national-archives.atlassian.net/jira/software/projects/DF/issues/DF-845
Applying the `tna-container` class on elements within the search section.
Review changes visually across viewports
> DF-845 wrap search results in tna container

- templates/search/blocks/search_filters.html
- templates/search/blocks/search_sort_and_view_options.html
Ticket URL:  https://national-archives.atlassian.net/browse/DF-853
Edits to the 'Sort by' dropdown element on search results pages - Desktop and mobile.
Check that the 'Sort by' dropdown reflects the changes listed in the ticket - Desktop and mobile.
> DF-853 Sort by changes

- pyproject.toml
- sass/includes/search/_catalogue-search-grid.scss
- sass/includes/search/_search-results.scss
- sass/includes/search/_search-results__list-card.scss
- templates/includes/records/record-details.html
- templates/records/record_detail.html
- templates/search/blocks/search_filters.html
- templates/search/blocks/search_results__list-card--grid.html
- templates/search/blocks/search_results__list-card.html
- templates/search/blocks/search_sort_and_view_options.html
- templates/search/featured_search.html
- templates/search/includes/results-details.html
Ticket URL: NA 
- Using Option [Sync option 1](https://github.com/nationalarchives/ds-wagtail/tree/etna-rosetta?tab=readme-ov-file#syncing-entna-rosetta-with-channges-from-develop)
- Syncs the develop changes with etna-rosetta.
Ways to looks-
- Changes come in from develop v/s etna-rosetta see the etna-rosetta branch :  This branch is [7 commits behind](https://github.com/nationalarchives/ds-wagtail/compare/etna-rosetta...develop) develop.
- Merge commit comments in [Merge branch 'develop' into chore/sync-22122023](https://github.com/nationalarchives/ds-wagtail/commits/chore/sync-22122023)
Look at the changes made in develop v/s etna-rosetta via the etna-rosetta branch :  This branch is [7 commits behind](https://github.com/nationalarchives/ds-wagtail/compare/etna-rosetta...develop) …
> CHORE: sync 22 12 2023 - develop into etna-rosetta

- templates/search/blocks/search_filters.html
Template updates
- restore missing bits
- format html
> DF-851:template updates

- LICENSE
Ticket URL: N/A
Add license file
Appears in root of project folder
> CHORE: Add license

- templates/includes/records/record-details.html
This PR updates the HTML for the Access Conditions field on the record details pages.
Open a record details page with Access Conditions and see that it is appearing in the front-end.
> Updated access_condition -> access_conditions

- .platform.app.yaml
Ticket URL: NA
on main
Add disk space to Platform.SH
+----------+---------+---------+---------+-----------+--------+
| Mount(s) | Size(s) | Disk    | Used    | Available | % Used |
+----------+---------+---------+---------+-----------+--------+
| logs     | 4 KiB   | 1.9 GiB | 1.1 GiB | 863.1 MiB | 55.3%  |
| media    | 1.1 GiB |         |         |           |        |
| tmp      | 16 KiB  |         |         |           |        |
+----------+---------+---------+---------+-----------+--------+
> Add disk space

- sass/includes/_iiif-viewer.scss
- scripts/src/iiif-viewer.js
Adjusts the settings for universal viewer
> Universal viewer refinements

- templates/records/record_detail.html
Straightforward change to update the class on Record viewer heading on the record detail page.
> Fix: Updates 'record viewer' heading styles to match others on page

- etna/articles/models.py
Ticket URL: [EDEV-99]
Using `tags` instead of `article_tag_names` so we return a list of tags instead of a concatenated string with `\n`s in it.
http://localhost:8000/api/v2/pages/189/
[EDEV-99]: https://national-archives.atlassian.net/browse/EDEV-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDEV-99: Article tags

- .platform/services.yaml
Ticket URL: [EDEV-102]
Increased the db disk size from 256 to 512 in `services.yaml` to increase our db size on Platform.sh
This will need to be deployed to develop to test
[EDEV-102]: https://national-archives.atlassian.net/browse/EDEV-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDEV-102: Increase Platform.sh DB size

- docs/developer-guide/project-conventions.md
Ticket URL: NA
Add doc for creating new branch
https://nationalarchives.github.io/ds-wagtail/developer-guide/project-conventions/
> CHORE:Update project conventions

- etna/ciim/apps.py
Ticket URL: NA
Add comment with expanded CIIM acronym
CIIM - Collections Information Integration Middleware
NA
> CHORE:Add comment with expanded CIIM acronym

- templates/records/record_detail.html
Updates 'series' link to go to the current series anchor, rather than the related records anchor.
> Change to 'series' record detail jumplink

- etna/api/urls.py
https://the-national-archives.sentry.io/issues/5498134756/?project=6377027
> Return 400 for preview when the required parameters are missing

- poetry.lock
Updated:
wagtail 6.1.2 -> 6.1.3
django 5.0.6 -> 5.0.7
djangorestframework 3.15.1 -> 3.15.2
urllib3 2.2.1 -> 2.2.2
> CHORE: Updated Python packages

- templates/collections/explorer_index_page.html
http://localhost:8000/explore-the-collection/
> Add Discovery search box to Explore the Collection index page

- .platform/routes.yaml
Ticket URL: NA
Enable cache route
> CHORE:Platform SH enable cache route

- etna/records/blocks.py
- etna/records/serializers.py
- templates/collections/explorer_index_page.html
Small release to main to fix the NoneType errors on main.
> Release to main
